### ISSUE TITLE
Limit filter does not affect behavior of Iter 

### ISSUE THREAD

**Issue by powerslacker** [stripe/stripe-go#1004]
Go: go1.12.6 darwin/amd64
Stripe Library: Stripe/v1 GoBindings/68.2.0

When fetching a collection (`Payouts`, `BalanceTransacation`) via `Client.List` returns an `Iter`.  When calling `Iter.Next` there is no check against the _limit_ parameter, which means the library will fetch the entire result set based on the other query parameters. This is very unclear as the [API docs use _limit_ as an example](https://stripe.com/docs/api/payouts/list?lang=go) and show it returning a small result set. 

It seems very odd that the limit parameter does not affect the behavior of `Iter.Next` since the library is iterating thru the results of what should be the parameters passed in. A limit of '10' would result in an HTTP request per 10 results fetched, yet would still fetch the ENTIRE result set — that seems like a strange use case in comparison to getting the first ten items in the result set.

If this behavior is intentional, then it should be documented in the README/ Godoc, along with any workarounds if they exist. 

If this behavior is not intentional, then `Iter` should respect the _limit_ parameter, and stop paging once the total result set has met the limit.

**Comment by remi-stripe** [comment]
@powerslacker Thanks a lot for the feedback. At the moment what `Limit` conftrols is the number of elements it fetches in a single page. This means that when you list Payouts, we will hit our API, then fetch 10 Payouts in the List back to you. When you use `Next()` we automatically return the next Payout we have in memory for this page. If you reached the last one we would then fetch a new page of Payouts with the same number of elements controlled by `Limit`.

This is documented in our API reference because Go only supports auto-pagination (and was the first one to do so): https://stripe.com/docs/api/pagination/auto?lang=go
