### ISSUE TITLE
Problem with dependencies: github.com/stripe/stripe-go/checkout/session and github.com/stripe/stripe-go/v71/form

### ISSUE THREAD

**Issue by gridanjbf** [stripe/stripe-go#1088]
go version go1.13.1 linux/amd64

Firstly i fetched  <pre>github.com/stripe/stripe-go/checkout/session</pre>
using:
<pre> govendor fetch github.com/stripe/stripe-go/checkout/session </pre>
which depends on:
<pre>github.com/stripe/stripe-go/v71/form </pre>
This module cannot be fetched using govendor
the command:
<pre> govendor fetch github.com/stripe/stripe-go/v71/form </pre>
does not fail but fills the vendor file with the following entries:
```json
{
			"path": "github.com/stripe/stripe-go/v71",
			"revision": "6866041f85936e1566fbbfcdde79e3350b27a9bd"
		},
		{
			"path": "github.com/stripe/stripe-go/v71/form",
			"revision": "6866041f85936e1566fbbfcdde79e3350b27a9bd"
		},

```
AND the vendor folder at the specified path is **empty**.
Hence, running the project results in:
cannot find package "github.com/stripe/stripe-go/v71/form" in any of:
**go paths here**

**Comment by brandur-stripe** [comment]
Hey there, the reason that doesn't work is that the `v71` in the package path is "virtual" in that it tells Go Modules what major version you're interested in. stripe-go V71 has migrated to Go Modules as they've been the stable and recommended packaging system in Go for quite some time now. See the notes in the CHANGELOG here:

https://github.com/stripe/stripe-go/blob/master/v71_migration_guide.md#go-modules

Unfortunately though, full Go module support does make things difficult for deprecated Go packaging tools like govendor. You have a couple options:

* Migrate to Go Modules. There are [detailed instructions on how to this here](https://blog.golang.org/migrating-to-go-module), and I can tell you first-hand that it's easier to do than you'd think because the Go module tool has automatic support for pre-existing packaging systems.
    
    Go Modules are the one and true packaging system in Go going forward, and you will have to move to them eventually — there's no realistic alternative. If you take a look at [govendor's README](https://github.com/kardianos/govendor), you'll see that it's been entirely replace by three lines that say not to use it anymore.
* You could fork the stripe-go repository and peg the master branch at v70. This is before Go Modules came in, and should work with your existing packaging tool.

I'd very much recommend the first option of course! Closing this out, but let us know if you have any other questions.

**Comment by gridanjbf** [comment]
> Hey there, the reason that doesn't work is that the `v71` in the package path is "virtual" in that it tells Go Modules what major version you're interested in. stripe-go V71 has migrated to Go Modules as they've been the stable and recommended packaging system in Go for quite some time now. See the notes in the CHANGELOG here:
> 
> https://github.com/stripe/stripe-go/blob/master/v71_migration_guide.md#go-modules
> 
> Unfortunately though, full Go module support does make things difficult for deprecated Go packaging tools like govendor. You have a couple options:
> 
> * Migrate to Go Modules. There are [detailed instructions on how to this here](https://blog.golang.org/migrating-to-go-module), and I can tell you first-hand that it's easier to do than you'd think because the Go module tool has automatic support for pre-existing packaging systems.
>   Go Modules are the one and true packaging system in Go going forward, and you will have to move to them eventually — there's no realistic alternative. If you take a look at [govendor's README](https://github.com/kardianos/govendor), you'll see that it's been entirely replaced by three lines that say not to use it anymore.
> * You could fork the stripe-go repository and peg the master branch at v70. This is before Go Modules came in, and should work with your existing packaging tool.
> 
> I'd very much recommend the first option of course! Closing this out, but let us know if you have any other questions.

Thanks for the quick reply, i will definitely migrate to gomodules.

**Comment by brandur-stripe** [comment]
> Thanks for the quick reply, i will definitely migrate to gomodules.

Awesome! And no problem. Good luck with the change.
