### ISSUE TITLE
Stripe Payment Intent Params takes int amount

### ISSUE THREAD

**Issue by vipulsodha** [stripe/stripe-go#1128]
I want to understand how do we pass float amounts to payment intent creation ?
When I try to create a payment intent using stripe go sdk, it requires amount in int64. But amount can be in floats. 

Is there anything I am missing here?

**Comment by remi-stripe** [comment]
@vipulsodha I'm going to close this issue since it's not really a bug with stripe-go itself. Instead, you should usually contact our support team if you have questions about our API that our documentation doesn't answer, you can contact them here: https://support.stripe.com/contact

To answer your question though, amounts are always integers on PaymentIntents because they are in the smallest currency unit. If you want to charge $10 USD, then you would pass the amount in the smallest currency unit (the cent) so $10 is 1000 cents. So you would pass `amount: 1000` and `currency: "usd"`. In stripe-go, it'd be `Amount: stripe.Int64(1000)` and `Currency: stripe.String(string(stripe.CurrencyUSD))`.
