### ISSUE TITLE
Feature request: Ability to include pricing data in Products package

### ISSUE THREAD

**Issue by gavinbd** [stripe/stripe-go#1159]
Version: github.com/stripe/stripe-go/v71 v71.44.0

The UI app is able to inject pricing data directly into a product list call as such: 

https://dashboard.stripe.com/v1/products?include%5B%5D=data.prices&expand%5B%5D=data.prices.data.tiers&limit=20

There seems to be no way to currently do this via the golang api as the Product struct doesnt contain a prices member at all.

Replication steps:

`
params := &stripe.ProductListParams{}

	params.IDs = products
	params.AddExpand("data.prices")
	params.AddExpand("data.prices.data.tiers")

	iter := s.client.Products.List(params)

	return iter.ProductList(), nil`

No pricing data is returned.

**Comment by remi-stripe** [comment]
@gavinbd Thanks for reaching out! This feature doesn't exist in our public API today which is why it's not available in stripe-go. If you look at the Product Create API [documentation](https://stripe.com/docs/api/products/create) you'll there is no `price_data` today.

This feature is special to the Dashboard to make the UI easier to interact with. In the API, your code would create a Product first and then for that Product you would create a Price.
