### ISSUE TITLE
[POST] Create Schedule Subscription is missing custom_fields in invoice settings

### ISSUE THREAD

**Issue by thaitanloi365** [stripe/stripe-go#1161]
![Screen Shot 2020-08-14 at 10 02 19 AM](https://user-images.githubusercontent.com/16873986/90209308-3f8b6180-de15-11ea-9cc4-3a4264013388.png)

Hello !,
I'm working on Stripe subscription using Golang.
In Stripe dashboard, I could add custom_fields in invoice settings. But I didn't see custom_fields in go sdk.
Please help me to resolve it, thanks.

**Comment by remi-stripe** [comment]
@thaitanloi365 Thanks for reaching out! At the moment, this feature is limited only to the Dashboard and it's not in our public API. That's why it's not in stripe-go yet because it's a feature we only support in the Dashboard.

I'd recommend reaching out to our support team directly to ask for support for this in your API and register your interest. You can contact them here: https://support.stripe.com/contact

**Comment by thaitanloi365** [comment]
@remi-stripe thanks you, I'll discuss with my team about that.
