### ISSUE TITLE
redirectToCheckout from go

### ISSUE THREAD

**Issue by skerkour** [stripe/stripe-go#1191]
Hi,

I'm trying to redirect my users to the Stripe `Checkout Session` directly from the backend (`stripe-go`) instead of using `stripe.redirectToCheckout` from Stripe.js.

I can't figure how to do this.

Feel free to redirect me to appropriate help and close the issue if it is out of context.

**Comment by remi-stripe** [comment]
@skerkour This is not something that we support in the API today which is why it's not in stripe-go. You have to do a client-side redirect at the moment. If we add a server-side redirect in the future we will definitely make it available in stripe-go.

I'd recommend registering your interest for this feature with our support team directly: https://support.stripe.com/contact

**Comment by remi-stripe** [comment]
For everyone watching this thread/issue, I wanted to mention that we just shipped this feature today. The `Session` resource now has a `url` [property](https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-url) that you can use to do a server-side redirect. We just shipped this in stripe-go version 72.51.0. You can now access the `URL` property on `Session` [here](https://github.com/stripe/stripe-go/blob/master/checkout_session.go#L447).

Over the next few weeks, we're going to update our docs to reflect this but I wanted to circle back quickly!

**Comment by skerkour** [comment]
Wow, this is absolutely great, thank you!
