### ISSUE TITLE
Customer object returning subscriptions as null

### ISSUE THREAD

**Issue by sdprimed** [stripe/stripe-go#1201]
I am using version 72 (latest) and am experiencing a new issue where the customer object is returning with a null subsciptions list. This was not happening with the previous version of the go library, and if I call the Stripe API directly in Postman, the customer object contains the subscription data for that customer.

**Comment by remi-stripe** [comment]
@sdprimed The stripe-go library is pinned to a specific API version and the latest major introduced the API version [2020-08-27](https://stripe.com/docs/upgrades#2020-08-27) which contains multiple changes related to Billing. One of those changes is to stop returning the list of Subscriptions on the Customer by default. This makes the API a lot faster for all cases where you don't need those.

The best option is to list subscriptions directly for your customer instead via the [API](https://stripe.com/docs/api/subscriptions/list). Otherwise, you can expand the subscriptions list because the property is now includable which is documented [here](https://stripe.com/docs/expand#includable-properties).

**Comment by sdprimed** [comment]
OK. That threw me off since it is still listed in the customer object. How do I list the subscriptions directly? I didn't see a golang API to retrieve the subscription list for a particular customer. There is sub.Get to get a single subscription object, but I didn't see how to retrieve all of the subscriptions for a customer. Thank you.

**Comment by remi-stripe** [comment]
@sdprimed just in case you were still stuck (though your message disappeared), we have a package for Subscription called `sub` and it has the `List` API as documented here: https://stripe.com/docs/api/subscriptions/list?lang=go

You can list all subscriptions for a given customer like this:

```
params := &stripe.SubscriptionListParams{
  Customer: stripe.String("cus_123"),
}
params.Filters.AddFilter("limit", "", "3")
i := sub.List(params)
for i.Next() {
  s := i.Subscription()
}
```
