### ISSUE TITLE
Use standard strings instead of stripe.String

### ISSUE THREAD

**Issue by eacp** [stripe/stripe-go#1211]
It would be better from the point of view of developers to just use `string` instead of `stripe.String`. The custom type is just a pointer to a string.  It would add readability to use Go standard `string` Instead of the custom one

**Comment by remi-stripe** [comment]
@eacp We use the standard string on property and parameters. We have to use `stripe.String` so that we can differentiate between parameters that were not initialized versus the ones being explicit empty string. Does that make sense?
You can read more about this here: https://github.com/stripe/stripe-go/issues/560

**Comment by brandur-stripe** [comment]
What Remi said — essentially, all of this is a workaround for Go's concept of zero values.

And to be clear, `stripe.String` is a function rather than a custom type — fields are just normal string pointers once they're on the structs.

**Comment by eacp** [comment]
So, if Go had a concept of Nullable Strings, or a way to check if a string was actually initialized in the code (like str.IsNull()), then this would be unnecesarry?

**Comment by brandur-stripe** [comment]
> So, if Go had a concept of Nullable Strings, or a way to check if a string was actually initialized in the code (like str.IsNull()), then this would be unnecesarry?

Yes.

Although to be fair, a string pointer (`*string`) is kind of a nullable string, and that's what we used.

**Comment by rollulus** [comment]
In case the Stripe guys haven't convinced you, @eacp, the aws go sdk does exactly the same, presumably for the same reasons. Also, if you have a string floating around already, e.g. in a variable, nothing prevents you to do `&yourString` instead of `stripe.String(yourString)`; both result in the required `*string`.

**Comment by alecbz** [comment]
> So, if Go had a concept of Nullable Strings, or a way to check if a string was actually initialized in the code (like str.IsNull()), then this would be unnecesarry?

Like @brandur-stripe said, `*string` is already basically that. `str.IsNull` is like `str == nil`.

AIUI the main impetus for a helper like `string.String` (and the many similar helpers in other libraries) is that you can't take the address of a string literal. E.g., if a function takes a string, you can do:

```go
func foo(s string) { ... }
foo("hello")
```

But if a function take a _nullable_ string (`*string`), you can't do something similar:

```go
func bar(s *string) { ... }
bar("hello") // doesn't work
bar(&"hello") // also doesn't work
```

you have to do something like:

```go
s := "hello"
bar(&s)
```

which can be tedious. So helpers like `stripe.String` are useful to allow:

```go
bar(stripe.String("hello"))
```

**Comment by yejia-stripe** [comment]
@eacp Closing this out as it seems to be resolved/has not had discussion in a while.
