### ISSUE TITLE
Sepa Credit Transfer missing in Source

### ISSUE THREAD

**Issue by entvia** [stripe/stripe-go#1219]
Hi! Sepa CT is in beta, but we have access to it. So, now the Source includes `sepa_credit_transfer` details. Please, include it to stripe.Source, if possible. Here is the link to docs and the response:

https://stripe.com/docs/sources/sepa-credit-transfer#testing-sepa-credit-transfer-payments

> {
  "id": "src_18cPLvAHEMiOZZp1YBngt7Yv",
  "object": "source",
  "currency": "eur",
  "flow": "receiver",
  "livemode": false,
  "receiver": {
    "address": "DE89370400440532013000",
    "amount_received": 0,
    "amount_charged": 0,
    "amount_returned": 0,
    "refund_attributes_status": "missing",
    "refund_attributes_method": "email"
  },
  "sepa_credit_transfer": {
    "iban": "DE89370400440532013000",
    "bank_name": "TEST BANK",
    "bic": "TESTDE00",
  },
  "owner": {
    "address": null,
    "email": "jenny.rosen@example.com",
    "name": null,
    "phone": null,
    "verified_address": null,
    "verified_email": null,
    "verified_name": null,
    "verified_phone": null
  },
  "status": "pending",
  "type": "sepa_credit_transfer",
  "usage": "reusable"
}

**Comment by remi-stripe** [comment]
@entvia We usually don't add beta features to stripe-go since the library is strongly typed and any API change would be a breaking change in the library or could cause deserialization errors.
On the other hand, `Source` is a bit special in the library and we already surface the type-specific details inside `TypeData` which exists here: https://github.com/stripe/stripe-go/blob/master/source.go#L314

This should allow you to access the details directly (though SEPA Credit Transfer is not a public feature and not something we discuss publicly usually!)

**Comment by entvia** [comment]
@remi-stripe thank you for prompt reply and the tip!
