### ISSUE TITLE
Payment_method on update customer does not exists

### ISSUE THREAD

**Issue by Crapulax** [stripe/stripe-go#1231]
API V71 offers ability to update payment_method on customer update. But this got rejected by Stripe server and indeed as per documentation there is no such possibility.

```
pm, err := s.sc.PaymentMethods.New(params)
	if err != nil {
		return nil, err
	}
if sCustomerId != nil {
		_, err := s.sc.Customers.Update(    // <---- this is going to fail with below error
			*sCustomerId, &stripe.CustomerParams{
				PaymentMethod: &pm.ID,
			},
		)
		if err != nil {
			return nil, err
		}
	}
```

[ERROR] Request error from Stripe (status 400): {"code":"parameter_unknown","doc_url":"https://stripe.com/docs/error-codes/parameter-unknown","status":400,"message":"Received unknown parameter: payment_method","param":"payment_method","request_id":"req_xxxxxxxxx","type":"invalid_request_error"}

Will use the paimentIntent instead I guess it will work (at least it is in doc)

Thanks

**Comment by remi-stripe** [comment]
@Crapulax Thanks for the report. The `CustomerParams` is used for both Create and Update APIs in the library today. The `PaymentMethod` parameter is supported on customer creation and not on customer update which is why you are getting this error. The best option is to either save the PaymentMethod automatically as part of a SetupIntent or PaymentIntent confirmation or use the PaymentMethod Attach API.

I hope this clarifies the issue!

**Comment by Crapulax** [comment]
Thanks for your fast answer Remi! It does work using PaymentIntent.
