### ISSUE TITLE
Use pointers for primitive fields

### ISSUE THREAD

**Issue by tarasyarema** [stripe/stripe-go#1258]
A few days ago I created an issue #1255 that mentioned that this package do not use `omitempty` tags in the JSON struct tags. Fast after, I realised that the `omitempty` tag was not the issue and I closed the issue. Now, the problem is actually on the non usage of pointers for the primitive fields on almost all the structs.

Why this can be a problem? Consider a `Coupon` object which has the `AmountOff` and `PercentOff` fields, which are numeric types (non pointers). If you look at the [API docs the example](https://stripe.com/docs/api/coupons/object) has the field `percent_off` set to `null`. Now, when you get the respective `stripe.Coupon` you will see that the `PercentOff` is set to `0`. This may seem like a minor issue at first, but this behaviour is not equivalent to the API nor to other language implementations. The problem is with Go zero values, hence the use of pointers is needed. If you change the `PercentOff` field to be `*float64` you will get a `nil` value for the example above.

This change may be really big (in fact we implemented it in our fork [here](https://github.com/Capchase/stripe-go)), and can generate a lot of breaking changes. Thus I understand that this may not be implemented in the near future. In the other hand, I consider important to have this issue for the package, as this problem is not about business logic nor specific implementations (which may arise to a custom implementation of the API client and not using this one), as basically you get may get data that it is not actually what the API returns.

For more information I created a post where I explain with more details the problem [here](https://tarasyarema.com/2021-03-01/stripe-drama?utm_source=gitstripe).

**Comment by brandur-stripe** [comment]
Hi Taras,

Thanks for the thoughtful write-up.

There's some historical context to this one in that I believe the original reason every field was made a non-pointer was largely accidental in that the author didn't think too about it much one way or the other, but that original design became entrenched as this library gained many users.

Some years back, we did a big overhaul of the project where we changed input parameters to all use pointer fields so that we could better represent null values. See the [RFC where this was discussed](https://github.com/stripe/stripe-go/issues/560).

At that time, we did also think about changing all these response fields as well, but didn't do. Part of the reason is that it would have been a breaking change on a truly colossal scale, but partly because there is a major usability downside to pointers in that you now need to perform a null check on every access to every field, which quickly becomes extremely verbose.

``` go
if coupon.AmountOff != nil {
    setDiscount(*coupon.AmountOff)
}
```

It's not ideal that it then becomes difficult to distinguish between a zero value versus a true null, but _in practice_, this turns out not to be that big of a problem with Stripe's API. For your `AmountOff` example, it's not unreasonable that upon seeing an `AmountOff` set to zero, you're dealing with an unset field, and should check `PercentOff` instead, or vice versa. Again, this isn't perfectly ideal, but in Go, which has no syntactic niceties for working against missing values, it's not a bad compromise.

Due to the side of breaking change and the downsides with respect to the ergonomics, we're not likely to make this change, so going to close out this issue.

**Comment by tarasyarema** [comment]
Thanks, @brandur-stripe for the excellent explanation and context. 

I highly agree that this is a really big change and it's not reasonable for the amount of users this package has. Also I agree on the verbosity pointer introduce, but for our use case we actually need exactly the same data that other language packages return, so we can not introduce the type of logic you commented about the `AmountOff` parameter. 

In the other hand, the Stripe API is really big and has tons of different structures, which made the _implement our own package_ almost impossible in terms of time (as we handle a lot of different responses). Hence we decided to fork and implement pointers for all responses, which, good for us, do not introduce the verbosity of them as saving the object to a db already handles it automatically.
