### ISSUE TITLE
Stripe Search?

### ISSUE THREAD

**Issue by amrnt** [stripe/stripe-go#1262]
Hi,

I've been working for sometime with Stripe. Recently I was looking into searching the customers which is possible only by email in `customer.List`.

Lately, I figured out that you have an undocumented(?) endpoint to preform searching under `/v1/search` which is using dashboard search: https://stripe.com/docs/dashboard/search.

I implemented a way to search in customers (at lease):

With the example code below:
* I want to understand if this endpoint is here to live?
* Is this something that would be implemented? Start a PR?

/Thanks

### search.go

```golang
package search

import (
	"net/http"

	stripe "github.com/stripe/stripe-go/v72"
	"github.com/stripe/stripe-go/v72/customer"
	"github.com/stripe/stripe-go/v72/form"
)

type client struct {
	B   stripe.Backend
	Key string
}

func getC() client {
	return client{stripe.GetBackend(stripe.APIBackend), stripe.Key}
}

// Customers ...
func Customers(params *stripe.CustomerListParams) *customer.Iter {
	return getC().searchCustomers(params)
}

func (c client) searchCustomers(listParams *stripe.CustomerListParams) *customer.Iter {
	return &customer.Iter{stripe.GetIter(listParams, func(p *stripe.Params, b *form.Values) ([]interface{}, stripe.ListContainer, error) {
		list := &stripe.CustomerList{}
		err := c.B.CallRaw(http.MethodGet, "/v1/search", c.Key, b, p, list)

		ret := make([]interface{}, len(list.Data))
		for i, v := range list.Data {
			ret[i] = v
		}

		return ret, list, err
	})}
}
```

### somewhere.go

```golang
	import "github.com/xxx/xxx/search"

	// search customers only
	query := []string{"is:customer"}
	// search email/phone
	query = append(query, "emailOrPhone")
	// search metadata
	query = append(query, fmt.Sprintf("metadata:%s=%s", "key", "value"))

	// other params?
	params := &stripe.CustomerListParams{}
	params.Filters.AddFilter("count", "", "100")
	params.Filters.AddFilter("query", "", strings.Join(query, " "))
	params.Filters.AddFilter("prefix", "", "false")
	params.Filters.AddFilter("facets", "", "false")

	// assuming results are the same as returned from `customer.List`
	s := search.Customers(params)
	for s.Next() {
		fmt.Println(tmp := s.Customer())
	}
```

**Comment by remi-stripe** [comment]
@amrnt Thanks for reaching out! This endpoint is definitely not something we consider public. It's an endpoint specific to the Dashboard and it's not an API we consider public in any way. We regularly make changes to the API and its data format and we would not consider those changes breaking in any way. You definitely shouldn't be relying on this endpoint in your own production code as it will break at any point in the future and has before.

Now, since we're discussing the Search API, we are actively working on a new API that will be public in the future and available in all our client libraries including stripe-go. We're just getting started on this work right now so it's not official and we don't have firm timelines yet. We're focusing on the ability to find customers by metadata as the first feature though which seems to map to what you're trying to achieve. I'll flag this internally so that the engineering team can follow up with you in the future once we're ready for beta-testers since your use-case might be a perfect fit.

I hope this helps!

**Comment by valcos-eb** [comment]
Hi @remi-stripe , I was looking for a way to retrieve connected accounts based on some advanced filtering (e.g., account status, disabled reason) and I've bumped into this issue. I wasn't able to find something useful in the documentation, so I wanted to ask you if there are some news on the new API you mentioned.

thanks!
