### ISSUE TITLE
Add Level 3 to PaymentIntents

### ISSUE THREAD

**Issue by coreymgilmore** [stripe/stripe-go#1263]
Providing Level 3 charge data is available via the "Charges" API using the ChargeParams.Level3 field.  However, providing Level 3 data is not available for the "Payment Intents" API.  Can this functionality be added?  It is helpful for reducing transaction costs an allows for better price negotiation.

**Comment by remi-stripe** [comment]
@coreymgilmore Passing Level 3 data on PaymentIntent is supported in the API but it is not available publicly yet. It's a feature that requires special access on your account for it to work. Because of this the stripe-go library does not officially support this feature yet. If you have access to the feature, the best option would be to use the `AddExtra` method on the library. Your code would look like this:
```
params := &stripe.PaymentIntentParams{
  Amount: stripe.Int64(100),
  Currency: stripe.String(string(stripe.CurrencyUSD)),
  PaymentMethodTypes: stripe.StringSlice([]string{
    "card",
  }),
}
params.AddExtra("level3[merchant_reference]", "55823")
params.AddExtra("level3[customer_reference]", "808080")
params.AddExtra("level3[shipping_address_zip]", "94110")
params.AddExtra("level3[shipping_from_zip]", "94117")
params.AddExtra("level3[shipping_amount]", "0")
params.AddExtra("level3[line_items][0][product_code]", "11234")
params.AddExtra("level3[line_items][0][product_description]", "First item")
params.AddExtra("level3[line_items][0][unit_cost]", "60")
params.AddExtra("level3[line_items][0][quantity]", "1")
params.AddExtra("level3[line_items][0][tax_amount]", "0")
params.AddExtra("level3[line_items][0][discount_amount]", "0")
params.AddExtra("level3[line_items][1][product_code]", "1124")
params.AddExtra("level3[line_items][1][product_description]", "Second item")
params.AddExtra("level3[line_items][1][unit_cost]", "40")
params.AddExtra("level3[line_items][1][quantity]", "1")
params.AddExtra("level3[line_items][1][tax_amount]", "0")
params.AddExtra("level3[line_items][1][discount_amount]", "0")

paymentintent.New(params)
```

If you don't have access, this is something you would discuss directly with our support team: https://support.stripe.com/contact

**Comment by coreymgilmore** [comment]
@remi-stripe 
Thanks for the info.  I understand this is a non-public feature but it seems odd that the Level3 info is included in the "Charges" API (for example, the types and fields exist) but then for the "Payment Intents" API we need to use `AddExtra`.

**Comment by remi-stripe** [comment]
@corey-stripe Agreed but that feature is public on Charges and part of the official API. We do want to change the design on PaymentIntents in the future, which is a lot harder when the feature is public for everyone. So for now it's "gated" and you have to request access so that the number of integrations relying it is small enough that we can make changes to the API in the future. We would make sure not to break any integrations when that happens but we wouldn't have the cost of maintaining 2 versions in client libraries for example.

**Comment by gilharo** [comment]
Hello @remi-stripe,

We are currently in the process of incorporating the suggested solution (utilizing the `Extra` in params) in our implementation. During testing, we successfully included `Level3Data` details in our request, and the response object received is of type `*stripe.PaymentIntent`. However, we are unable to locate a specific field within this object that allows us to verify whether the `Level3Data` has been transmitted.

Is there a method to retrieve the `Level3Data` from the response object?

Thank you!

**Comment by remi-stripe** [comment]
The readme has [this section](https://github.com/stripe/stripe-go?tab=readme-ov-file#properties) which covers in details how to retrieve information that isn't directly in the type for the resource.
