### ISSUE TITLE
trying to determine default payment method

### ISSUE THREAD

**Issue by swys** [stripe/stripe-go#1284]
Please let me know if this isn't the correct place to pose this question. I'm seeing the same behavior returned from the REST api as well as from the go library so this might just be a misunderstanding on my part.

Environment : 
```
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

go version go1.15.12 linux/amd64
```
from go.mod : 
```
github.com/stripe/stripe-go/v72 v72.30.0
```

I'm trying to find the best way to determine which credit card is set to default on a customer's account. When calling the customer api `/v1/customers` I can see there is a couple of places I'd expect would give me the default card : 

possibly this : 
` "default_source": "card_1IrxdnCe3AMLpiXNK2qMWnsw",`
and
```
    "invoice_settings": {
        "custom_fields": null,
        "default_payment_method": "pm_1IMQn1Ce3AMLpiXN4yaDL53F",
        "footer": null
    },
```

However, I'm seeing some inconsistent behavior. In the stripe UI I can look at a customer and see what payment methods they have attached to their account. I have a customer that has 2 test cards (this account is in test mode, not live mode) and I have a visa card set as default. When I retrieve the customer the above values are shown. As a quick test I go to the stripe UI and I set the other card as default (its a mastercard) but when I call the customer api again I get below : 

```
"default_source": "card_1IrxdnCe3AMLpiXNK2qMWnsw",
...
    "invoice_settings": {
        "custom_fields": null,
        "default_payment_method": null,
        "footer": null
    },
```
Now the `default_payment_method` is prop is null. If I set the default card back to the visa card in the stripe UI, the value of `default_payment_method` populates again with the expected card id.

I would expect the value of the `default_payment_method` prop to match the card id that I set as default via the stripe UI, but I either get `null` or an expected card id. Also the value of `default_source` doesn't change no matter which card I set as default in the stripe UI.

So I'm wondering what is the best way to determine the default card value by using the stripe api? Am I not using the correct api for this? I thought it would be the customer api since when I checked the paymentMethods api I could not find anything that indicated the default card.

Also is this expected behavior that the api would return `null` for `default_payment_method` for one card and then return a valid card id if the default is switched? I would expect the value of this prop should be populated to match the card id of the current default card and when I switch the default from card A to card B the values returned from the api would also update accordingly.

**Comment by paulasjes-stripe** [comment]
Issues on this repo are meant for bugs with the actual library, so I'm closing this. For integration questions you should reach out to Stripe support directly at https://support.stripe.com/contact.

To unblock you, there is no concept of a "default PaymentMethod" in the same way there are default sources. Updating a customer's source will automatically set that source as the default to be used in future transactions. With PaymentMethods you have to explicitly provide the PaymentMethod ID when creating payments.

The exception is invoice settings, where you can provide a default PaymentMethod to be used for invoices (i.e. recurring payments).

The behaviour in the dashboard you're seeing is expected when you set a legacy object (i.e. a card that started out as a Source instead of a PaymentMethod) to be a customer's default by clicking the "set as default" button. I suspect that the Visa card is a PaymentMethod and the Mastercard a Source, hence why setting the latter as the default won't update the `default_payment_method` field.
