### ISSUE TITLE
Get customer api response sources is nil.

### ISSUE THREAD

**Issue by Swati661989** [stripe/stripe-go#1300]
I have created a customer with token  stripe customer created properly on stripe but in the response of create customer & get customer API sources is nil. It is changed in the new release ? or there is something wrong with the response.

**Comment by remi-stripe** [comment]
This is expected behaviour as the customer's cards are not returned in the API by default anymore. This is a change we made in the most recent API version [2020-08-27](https://stripe.com/docs/upgrades#2020-08-27):
> The sources property on Customers is no longer included by default. You can expand the list but for performance reasons we recommended against doing so unless needed.

We recommend not using this anymore and instead moving off of Token and Charges onto the PaymentIntent and PaymentMethod APIs. This comes with the [List PaymentMethods API](https://stripe.com/docs/api/payment_methods/list).

If you want to get the card on creation you will need to include the property like this:
```
params := &stripe.CustomerParams{}
params.SetSource("tok_123")
params.AddExpand("sources")
c, _ := customer.New(params)
```
