### ISSUE TITLE
Product type has an undocumented `Caption` field

### ISSUE THREAD

**Issue by abh** [stripe/stripe-go#1387]
The `product.Caption` field isn't documented anywhere I can find.

I am guessing it's from an old API version and should have been removed?

**Comment by remi-stripe** [comment]
Github issues should be limited to bugs with the library itself. This is a question about our API and should be directed to our support team [here](https://support.stripe.com/contact) though you can always chat with developers on Discord [here](https://stripe.com/go/developer-chat) otherwise.

To answer your question though, yes this is a legacy property from when products were created with `type: 'good'` for the legacy Orders API. This property is not really used anymore but we haven't done an API version to clean up for now and just undocumented it.
