### ISSUE TITLE
`SubscriptionItem` struct missing `Price` object.

### ISSUE THREAD

**Issue by danthegoodman1** [stripe/stripe-go#1418]
I noticed that the `SubscriptionItem` struct is missing the `price` field as found here: https://stripe.com/docs/api/subscriptions/object#subscription_object-items-data-price

**Comment by remi-stripe** [comment]
Looking at the `SubscriptionItem` resource I see `Price` defined [here](https://github.com/stripe/stripe-go/blob/master/subitem.go#L120) as expected. Can you clarify what you think is missing?

**Comment by danthegoodman1** [comment]
Forcing a `github.com/stripe/stripe-go/v72` import worked. Strange that it took that `v70` version by default...

**Comment by remi-stripe** [comment]
Yeah that version was released in April 2020 ([changelog](https://github.com/stripe/stripe-go/blob/master/CHANGELOG.md#70150---2020-04-14)) so you're quite behind and the Price API was added after that. You'll want to upgrade to the latest, while looking at all breaking changes since we're now at 72.86.0.

**Comment by danthegoodman1** [comment]
Yeah, that was the first time I pulled the stripe package on this machine so not sure how that become the default version that was pulled...

**Comment by remi-stripe** [comment]
The reason it had v70 is because we moved to go modules starting with the major version v71.0.0 and your code likely did not opt into that.

**Comment by danthegoodman1** [comment]
Ah thanks for the heads up!
