### ISSUE TITLE
Allow Specification of API version

### ISSUE THREAD

**Issue by bumberboy** [stripe/stripe-go#1435]
Hello there

Apparently API version shouldn't be a constant!

https://stripe.com/docs/payments/paynow/accept-a-payment

I'm trying to follow this doc to test out the beta for a payment method available in Singapore.

The instruction includes appending to the api version a tag:

```python
stripe.api_version = '2020-08-27; paynow_beta=v1'
```

I'm wondering if it is possible for you guys to temporarily create a separate branch with the api version set to that?

Thank you

**Comment by remi-stripe** [comment]
@bumberboy statically typed client libraries (stripe-go, stripe-java and stripe-dotnet) don't support betas like this and we don't plan to add support for now to override the API version. Betas often evolve over time and introduce breaking API changes which could lead to a problem deserializing the resource/data with the library itself unfortunately which prevents us from supporting betas in those. While we could support overriding the version in simple cases, it'd quickly break for most betas which is why we haven't yet added this.

Once PayNow gets released publicly, it will be supported by all client libraries including stripe-go.

I'm closing this issue as it's discussing a secret feature that isn't documented publicly (unless your account is part of the beta) but you can talk to our support team if you need more details: https://support.stripe.com/contact
