### ISSUE TITLE
Missing 3DS fields in IssuingAuthorizationVerificationData

### ISSUE THREAD

**Issue by 1ststack** [stripe/stripe-go#1458]
### Describe the bug

Hello Team,

The following code missing 3ds verification_data.

https://github.com/stripe/stripe-go/blob/d663155d0c78f0adf2e6d8b88da6ca3609f17bf2/issuing_authorization.go#L188

```
type IssuingAuthorizationVerificationData struct {
	// Whether the cardholder provided an address first line and if it matched the cardholder's `billing.address.line1`.
	AddressLine1Check IssuingAuthorizationVerificationDataCheck `json:"address_line1_check"`
	// Whether the cardholder provided a postal code and if it matched the cardholder's `billing.address.postal_code`.
	AddressPostalCodeCheck IssuingAuthorizationVerificationDataCheck `json:"address_postal_code_check"`
	// Whether the cardholder provided a CVC and if it matched Stripe's record.
	CVCCheck IssuingAuthorizationVerificationDataCheck `json:"cvc_check"`
	// Whether the cardholder provided an expiry date and if it matched Stripe's record.
	ExpiryCheck IssuingAuthorizationVerificationDataCheck `json:"expiry_check"`
}
```

https://stripe.com/docs/issuing/3d-secure#prevent-fraud

https://stripe.com/docs/api/issuing/authorizations/object#issuing_authorization_object-verification_data

```
{
	"id": "iauth_1KxrqNLxDGH5lfJGpr73s9K3",
	"object": "issuing.authorization",
	............
	"verification_data": {
	  "address_line1_check": "not_provided",
	  "address_postal_code_check": "not_provided",
	  "cvc_check": "not_provided",
	  "expiry_check": "match",
	  "three_d_secure": null <- missing
	},
	"wallet": null
  }
```

All the best,

Aaron

### To Reproduce

See Describe

### Expected behavior

```
type IssuingAuthorizationVerificationData struct {
    // Whether the cardholder provided an address first line and if it matched the cardholder's `billing.address.line1`.
    AddressLine1Check IssuingAuthorizationVerificationDataCheck `json:"address_line1_check"`
    // Whether the cardholder provided a postal code and if it matched the cardholder's `billing.address.postal_code`.
    AddressPostalCodeCheck IssuingAuthorizationVerificationDataCheck `json:"address_postal_code_check"`
    // Whether the cardholder provided a CVC and if it matched Stripe's record.
    CVCCheck IssuingAuthorizationVerificationDataCheck `json:"cvc_check"`
    // Whether the cardholder provided an expiry date and if it matched Stripe's record.
    ExpiryCheck IssuingAuthorizationVerificationDataCheck `json:"expiry_check"`
    // Add this to parse 3ds result from stripe rest API
    ThreeDSecure IssuingAuthorizationVerificationThreeDSecure `json:"three_d_secure"` // <- add
}

// added this for parse result
type IssuingAuthorizationVerificationThreeDSecureResult string 

// added this for parse result
type IssuingAuthorizationVerificationThreeDSecure struct {
    Result IssuingAuthorizationVerificationThreeDSecureResult `json:"result"` 
}
```

So that I can access 3ds fields directly not parse raw event data :)

### Code snippets

```Go
N/A
```

### OS

All OS

### Go version

go1.18.1

### stripe-go version

v72

### API version

All

### Additional context

N/A

**Comment by remi-stripe** [comment]
@1ststack The `verification_data[three_d_secure]` property is not really missing in the library, it's just not a public feature yet. We don't add secret/gated/beta features to stripe-go since those could still change ahead of public release and that would be a breaking change. If you look at the official API reference [here](https://stripe.com/docs/api/issuing/authorizations/object#issuing_authorization_object-verification_data) you'll see that `three_d_secure` is either missing (in incognito) or present with a `Preview` tag if you're logged in.

Once the feature is released publicly it will be added to stripe-go automatically on our end. I'd recommend working with our support team to ask for a timeline as to when it will be released.

In the meantime, you can use `LastResponse.RawJSON` to access secret properties that our API returns but the library doesn't handle. It's not perfect but it might help so here's a basic example:

```
s, _ := sub.Get("sub_123", nil)

var rawData map[string]interface{}
_ = json.Unmarshal(s.LastResponse.RawJSON, &rawData)
int64(rawData["created"].(float64))

transferData, ok := rawData["transfer_data"].(map[string]interface{})
if ok {
  transferData["amount_percent"].(float64))
}
```
