### ISSUE TITLE
Charge.Customer has 2 types

### ISSUE THREAD

**Issue by haotsai101** [stripe/stripe-go#1489]
### Describe the bug

We received `PaymentIntent.succeeded` from webhook. We are trying to decode the paymentIntent object. But we got the error  `* 'Customer' expected a map, got 'string'`. The webhook is giving us `string` as `PaymentIntent.Charges.Data[0].Customer`, but the actual type is `*Customer`

### To Reproduce

1. Get webhook PaymentIntent event
2. Decode it with `mapstructure.Decode(event.Data.Object, &paymentIntent)`

### Expected behavior

Expect to receive the paymentIntent object

### Code snippets

```Go
paymentIntent := stripe.PaymentIntent{}
err := mapstructure.Decode(event.Data.Object, &paymentIntent)
if err != nil {
	return fmt.Errorf("unable to decode event - %+v", err)
}
```

### OS

macOS

### Go version

Go v1.18.2

### stripe-go version

v72.115.0

### API version

2019-12-03

**Comment by remi-stripe** [comment]
In the API, a lot of our properties can be "expanded" ([doc](https://stripe.com/docs/expand)). This means that our API will return the id of another object such as `customer: 'cus_123'` and that id can be expanded to return the entire resource itself in its place so `customer: {id: 'cus_123', object: 'customer', ...}`.

This means the property can have two types, either a `string` or the relevant object like `*Customer`. Each library handles this differently and stripe-go has its own way. The idea is that we always assume the entire object could be returned, or just the id, and in both cases we deserialize it into `*Customer` and either just set `ID` or set the whole thing.

I think the problem is due to how you deserialize the JSON. You should be following what our [quickstart guide](https://stripe.com/docs/webhooks/quickstart) recommends where you deserialize the whole Event object and then you can use `evt.Data.Raw` like this:

```
	paymentIntent := stripe.PaymentIntent{}
	json.Unmarshal(event.Data.Raw, &paymentIntent)
```

Can you clarify if that would work for you?
