### ISSUE TITLE
Shipping/Address type conversion hell

### ISSUE THREAD

**Issue by steadicat** [stripe/stripe-go#155]
I’m having trouble understanding the logic of some of the types used in this API.

There are currently four nearly identical structs that contain shipping information (name, address, phone):

```Go
type Shipping struct {
    Name    string  `json:"name"`
    Address Address `json:"address"`
    Phone   string  `json:"phone"`
}

type CustomerShippingDetails struct {
    Name    string  `json:"name"`
    Address Address `json:"address"`
    Phone   string  `json:"phone"`
}

type ShippingParams struct {
    Name    string
    Address *AddressParams
    Phone   string
}

type ShippingDetails struct {
    Name     string  `json:"name"`
    Address  Address `json:"address"`
    Phone    string  `json:"phone"`
    Tracking string  `json:"tracking_number"`
    Carrier  string  `json:"carrier"`
}
```

I find myself having to convert between these *a lot*. I realize that in some cases Go lets you convert similar structures by casting, but that works only half the time because of subtle incompatibilities. For example `ShippingParams(Shipping)` fails because one takes `Address` and the other takes `AddressParams`. To make things worse, `Address` and `AddressParams` are also subtly incompatible:

```Go
type Address struct {
    Line1   string `json:"line1"`
    Line2   string `json:"line2"`
    City    string `json:"city"`
    State   string `json:"state"`
    Zip     string `json:"postal_code"`
    Country string `json:"country"`
}

type AddressParams struct {
    Line1      string
    Line2      string
    City       string
    State      string
    PostalCode string
    Country    string
}
```

Can you spot it? Yeah, `PostalCode` vs `Zip`. This causes me to have to copy every field manually in both `*Address` and the `*Shipping` that contains it, if e.g. I want to create a customer and an order (or a charge) using the same shipping info.

Is there any way to make these structs compatible? Or any other way to make working with these easier?

**Comment by brandur** [comment]
@steadicat Thanks for getting this issue going!

+1 that the state of today is pretty bad. I think that in general though, we'll actually want to keep these structs different so that if some minor incompatibilities in addresses are introduced between endpoints (which already exist) we can deal with them in a sane way.

Want we need to fix though is to make these actually inconsistent in how they're named and referenced. My initial thought is that every type of resource should just get its own shipping type so that there's never any guesswork involved in what gets used. This might look like:

```
Shipping                -> OrderShipping
CustomerShippingDetails -> CustomerShipping
ShippingParams          -> OrderShipping
ShippingDetails         -> ChargeShipping
```

> I find myself having to convert between these a lot.

This would still seem to be a problem though. Can you detail some of the standard types of address conversions that you run into frequently? It's possible that we can provide some helper methods to make these a little less painful.

> Can you spot it? Yeah, PostalCode vs Zip. This causes me to have to copy every field manually in both *Address and the *Shipping that contains it, if e.g. I want to create a customer and an order (or a charge) using the same shipping info.

Yeah, this isn't great to say the least. I've put in a pull at #158 to see what people think about making these consistent.

**Comment by brandur** [comment]
One solution that's a little further afield which I didn't mention is that it could be conceivably possible for the various API functions to accept an interface instead of a concrete parameters implementation, which might allow us to create a meta-shipping struct that tries to be automatically compliant with as many of the endpoints as possible. (But I suspect that the cost here might outweigh the benefit.)

@steadicat As stated above, we're working toward a more consistent library, but I don't intend to take immediate action on this issue so I'm going to close it out for now. Let me know if you have any ideas around possible helpers for shipping conversion that we could add which might be beneficial for the particularly well-worn paths, or any other thoughts. Thanks!
