### ISSUE TITLE
Webhook had no valid signature

### ISSUE THREAD

**Issue by ThinhNV991** [stripe/stripe-go#1593]
### Describe the bug

I got error with gin
"webhook had no valid signature"

### To Reproduce

same code

### Expected behavior

I got an error message: "webhook had no valid signature"

### Code snippets

```Go
func (ctl *SuggestionCtl) StripeWebhook(c *gin.Context) {
	payload, err := c.GetRawData()
	if err != nil {
		response.RespondError(c, err)
		return
	}
	event, err := webhook.ConstructEvent(payload, c.GetHeader("Stripe-Signature"), "whsec_xxxxx")

	if err != nil {
		response.RespondError(c, err)
		return
	}

	response.RespondSuccess(c, nil, "OK")
}
```

### OS

macos

### Go version

go version go1.19 darwin/amd64

### stripe-go version

v74

### API version

2022-11-15

**Comment by remi-stripe** [comment]
@ThinhNV991 Github issues should be limited to bugs with the stripe-go library. This is instead and integration support question better directed at our support team: https://support.stripe.com/contact

90% of the time, the issue is due to using the wrong secret for the WebhookEndpoint so you need to triple check this. If you use the CLI, the secret is different in the CLI vs what you see in the Dashboard for example. 9% of the time the issue is that you are not handling the exact raw JSON we (Stripe) sent you. For example you have something in your code/framework that sees a JSON body and deserializes it for you to be helpful and then it gets re-serialized when you need to access it but it isn't exactly the body we sent you. Since those have to match exactly up to the order of properties, spacing, etc. you need to make sure you use the raw POST body that your server received.
