### ISSUE TITLE
Standard syntax for referencing AccountID, Customer, Recipient

### ISSUE THREAD

**Issue by collinglass** [stripe/stripe-go#164]
There should be a standard syntax for referencing the structs, either:

Account, Customer, Recipient

OR

AccountID, CustomerID, RecipientID

**Comment by brandur** [comment]
Yes! Agreed that this has unfortunately become a huge mess.

CC @stripe/api-libraries Mini-proposal: make parameters _without_ an "ID" suffix the one true way forward because that's how they look in the actual API and because many of the parameters are already in that format. I don't think renaming existing *ID parameters is worse it for now, but we should consider if we ever need to make a large breaking change at some point in the future. Thoughts?

**Comment by kyleconroy** [comment]
== 

Since most of these resources can be expanded, we should always use a struct instead of an ID.

**Comment by brandur** [comment]
@kyleconroy Cool, thanks!

@collinglass I'm going to close this out for now, but we'll keep an eye open for it during the review of future integrations. Thanks for bringing the problem to our attention.

**Comment by collinglass** [comment]
No problem, the [BankAccountParams](https://github.com/stripe/stripe-go/blob/master/bankaccount.go#L14-L19) has Account and AccountID, which is particularly confusing.

**Comment by brandur** [comment]
> No problem, the BankAccountParams has Account and AccountID, which is particularly confusing.

Yeah, that's pretty bad. I've added a small amount of documentation in #170 to try and improve this situation a bit.
