### ISSUE TITLE
Checkout Session Type is Inconsistent with the Typescript Type

### ISSUE THREAD

**Issue by mmacheerpuppy** [stripe/stripe-go#1667]
### Describe the bug

I want to parse a Typescript Checkout Session as part of a migration from Typescript to Go for client work. What I have found is I need to create my own structs that match the Typescript Checkout Session fields because the Stripe API client for Go does not parse the response accurately.

Perhaps this is not a bug because the organization of the SDKs does not necessarily have to be identical (I am not sure about this, as it is a decision made by Stripe). However, this makes the migration from a TypeScript backend to a Go backend very tedious when front-end clients rely on the equality of type information. 

As an example, the amount_total and PaymentIntent should not be considered equal in concept because Stripe payments can be made without an intent. So, which field should I choose to obtain the `amount_total`? Either this is a bug, or this is unclear (which I think, is a bug).

![image](https://github.com/stripe/stripe-go/assets/8885269/5e215ea9-84c2-4d27-af9a-09bc39cec83b)

### To Reproduce

1. Consume to `Stripe.CheckoutSessions.New(...)` in Stripe-go
2. Consume `await stripe.checkout.sessions.create(params);`
3. Find that the information in each SDK does not match because of the way the types consume data from the API. In particular I want the `amount_total` field. 

### Expected behavior

Types contain the same fields or replaceable fields

### Code snippets

```Go
See screenshot
```

### OS

any

### Go version

1.20

### stripe-go version

v70.15.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
Hey @mmacheerpuppy ! The stripe-go library supports the `amount_total` property the same way the stripe-node library does. If you look at the code on master [here](https://github.com/stripe/stripe-go/blob/master/checkout_session.go#L2316) you can see: 
```
type CheckoutSession struct {
	APIResource
	// When set, provides configuration for actions to take if this Checkout Session expires.
	AfterExpiration *CheckoutSessionAfterExpiration `json:"after_expiration"`
	// Enables user redeemable promotion codes.
	AllowPromotionCodes bool `json:"allow_promotion_codes"`
	// Total of all items before discounts or taxes are applied.
	AmountSubtotal int64 `json:"amount_subtotal"`
	// Total of all items after discounts and taxes are applied.
	AmountTotal  int64                        `json:"amount_total"`
	AutomaticTax *CheckoutSessionAutomaticTax `json:"automatic_tax"`
```

In your issue you mentioned you are on stripe-go's version v70.15.0. That version was released over 3 years ago back in April 2020 as you can see on the changelog [here](https://github.com/stripe/stripe-go/blob/master/CHANGELOG.md#70150---2020-04-14). Since you use such an old version of the library, you can only access the properties/parameters/APIs that existed back in April 2020 and `amount_total` was not yet shipped at the time.

Since that version, stripe-go has been constantly updated to support newer APIs and API versions so you need to make sure you are upgrading to the latest which is currently v74.21.0 that we released just yesterday. You can also refer to all our migration guides to handle the breaking changes for each major versions: [71.*](), [73.*](https://github.com/stripe/stripe-go/wiki/Migration-guide-for-v73) and [74.*](https://github.com/stripe/stripe-go/wiki/Migration-guide-for-v74).

You're likely blocked on that old version because you didn't realize we require using go modules since v71.* for stripe-go to work. See our installation guide [here](https://github.com/stripe/stripe-go/tree/master#installation).

**Comment by mmacheerpuppy** [comment]
Classic versioning issue, thanks so much for being a good citizen and helping me @remi-stripe

**Comment by remi-stripe** [comment]
Of course! That change to go module has tripped up a lot of developers since we made the move unfortunately.
