### ISSUE TITLE
Upcoming invoice API bug

### ISSUE THREAD

**Issue by xrmh-lu** [stripe/stripe-go#1671]
### Describe the bug

When changing from an existing subscription to another subscription, the duration of the coupon(e.g. one month)  less than the subscription end period of the upcoming plan(e.g. one year) change, the coupon used will be ineffective, i.e. no discount information will be returned.

Although the upcoming invoice does not show the discount information, the actual change of subscription is used.

### To Reproduce

step 1: Start by creating a general subscription with a monthly cycle.
step 2: Create a coupon for 1 month.
step 3:Update the monthly plan in step 1 to an annual plan and use the coupon.

`curl 'https://api.stripe.com/v1/invoices/upcoming?customer=cus_LA1cjMfX***&subscription=sub_1NGBfmCLGda*****(step 1)**&coupon=PTLIB***(**step 2)**&subscription_items[0][deleted]=true&subscription_items[0][id]=si_O2GCTu59n***&subscription_items[1][price]=price_1K4G28CLGday4gEJV*****(step 3, yearly plan)**&subscription_items[1][quantity]=5&automatic_tax[enabled]=true'
`

### Expected behavior

Discounts should be displayed on upcoming invoices whenever a coupon is used, not because the coupon cut-off period is less than the subscription cut-off period.

### Code snippets

```Go
curl 'https://api.stripe.com/v1/invoices/upcoming?customer=cus_LA1cjMfX***&subscription=sub_1NGBfmCLGda***&coupon=PTLIB***&subscription_items[0][deleted]=true&subscription_items[0][id]=si_O2GCTu59n***&subscription_items[1][price]=price_1K4G28CLGday4gEJV***&subscription_items[1][quantity]=5&automatic_tax[enabled]=true'
```

### OS

All

### Go version

ALL

### stripe-go version

ALL

### API version

ALL

### Additional context

a serious bug

**Comment by remi-stripe** [comment]
Hey @xrmh-lu! Github issues should be limited to bugs with the stripe-go library itself. The report you have seem to be more about understanding how proration and coupon work together during a Subscription update and this is better directed at our support team instead. You can contact them [here](https://support.stripe.com/contact) and provide detailed examples of what you are seeing in the API versus what you are expecting so that they can help you.
