### ISSUE TITLE
How do you want to handle setting Default cards with managed accounts?

### ISSUE THREAD

**Issue by collinglass** [stripe/stripe-go#171]
The BankAccountParams struct has a [Default field](https://github.com/stripe/stripe-go/blob/master/bankaccount.go#L29) to handle the default card. However, Cards are shared between customers, recipients and accounts and customers and recipients update their default cards [through the customer and recipient endpoints](https://stripe.com/docs/api#create_card).

On the same note, currency is also not in CardParams.

**Comment by brandur** [comment]
Thanks for getting the conversation started! Do you think that the answer here is something other than adding a `DefaultForCurrency` parameter to `CardParams` (or something close to that)?

**Comment by collinglass** [comment]
It solves it for now. It's consistent with bank accounts.

**Comment by collinglass** [comment]
I have a bigger question, which probably deserves it's own issue or discussion elsewhere. Why are there two separate entities for customer and account? We had to create a stripe account and stripe customer for every one of our users. And then juggle between customer cards, account card and account bank accounts.

**Comment by brandur** [comment]
Hey @collinglass!

> I have a bigger question, which probably deserves it's own issue or discussion elsewhere. Why are there two separate entities for customer and account? We had to create a stripe account and stripe customer for every one of our users. And then juggle between customer cards, account card and account bank accounts.

Hm, there might be some confusion here, but customers and accounts and supposed to be pretty separate ideas. A customer resource is something that a merchant can create in order to track a customer who's making transactions through that merchant. An account on the other hand, is for use [with Stripe Connect](https://stripe.com/docs/connect) and is designed to help a merchant accept payments on behalf of somebody else. A good example is Lyft: every driver gets an account and the parent Lyft account is able to accept charges on behalf of them as Lyft customers get rides from any of those drivers.

If you're not doing some platform-related that requires those Connect features, you probably shouldn't have to create accounts. Does that help clear things up at all?
