### ISSUE TITLE
Payout object: include `trace_number`

### ISSUE THREAD

**Issue by Preskton** [stripe/stripe-go#1723]
### Is your feature request related to a problem? Please describe.

As a consumer of the stripe-go library, I would like `Payout.trace_number` to be included when querying Stripe for payout data. This number (almost always?) ends up embedded in the "description" or "reference number" when a payout actually hits the destination bank. Having this data would significantly improve the accuracy of reconciliations between Stripe & bank accounts.

### Describe the solution you'd like

I would like `trace_number` to be included on the `Payout` object.

When looking at the actual data that comes back from stripe when viewing a single payout's detail, `trace_number` is present (and presented in the UI).

### Describe alternatives you've considered

I could use date & amount to reconcile between my bank account and Stripe, but because the transaction date & expected date are an estimate for when the payment will hit the bank, it's not always accurate.

**Comment by remi-stripe** [comment]
@Preskton Github issues are limited to bugs and feature requests for the library itself. `trace_number` is not a feature on our API (at least not publicly) and that's why it's not in client libraries/SDKs like stripe-go. This would be a feature request better directed to our support team: https://support.stripe.com/contact

**Comment by Preskton** [comment]
Makes sense, thank you for the redirect.
