### ISSUE TITLE
Checkout Session is missing the `invoice_creation` field

### ISSUE THREAD

**Issue by bonzzy** [stripe/stripe-go#1766]
### Is your feature request related to a problem? Please describe.

When creating the checkout session for one time payment, based on the docs, Stripe doesn't auto generate the invoice. At the moment without the invoice there is not `price_id` anywhere on the events so it is impossible to know which product was purchased just by looking at the events.
Stripe docs suggest manually generating the invoice and there is a field when using the raw API `invoice_creation
` which is missing on the CheckoutSession.

### Describe the solution you'd like

`invoice_creation` should be added as an param on the `CheckoutSessionParams` struct.
Something like `CheckoutSessionParams.InvoiceCreationParams`, and also `CheckoutSessionParams` should have a prop key `InvoiceCreation`.

### Describe alternatives you've considered

Alternative is manually creating the invoice on the payment complete which is just an extra call to Stripe API.

**Comment by remi-stripe** [comment]
@bonzzy The `InvoiceCreation` feature already exists as you can see [here](https://github.com/stripe/stripe-go/blob/ea2313acf56d0922953e3ea61c64a06bd991b8a6/checkout_session.go#L1757). It shipped months ago in 74.7.0 as you can see in the [changelog](https://github.com/stripe/stripe-go/blob/master/CHANGELOG.md#7470---2023-02-02).

My guess is that your code is on an older version of the library which is why you are not seeing it. Make sure to use go modules to use the most recent version as documented [here](https://github.com/stripe/stripe-go#installation).

Additionally, you don't need to use this feature to know what is being bought. The Checkout Session API has a `LineItems` property which contains all the line items included in that Session. They are not returned by default but can be accessed using the Expand feature as documented [here](https://stripe.com/docs/expand#includable-properties).

Overall, this is more an integration support question and better directed to our support team: https://support.stripe.com/contact
