### ISSUE TITLE
PlanProductParams for a new plan of an existing product does not behave like the spec

### ISSUE THREAD

**Issue by anastasop** [stripe/stripe-go#1774]
### Describe the bug

I create a product and then i try to add a new plan for it. I get the error message `Product already exists`. I was expecting no errors and a new plan to be created. Instead i get an error `Product already exists`

### To Reproduce

1. create a product
2. try to create a new plan for this product. Provide only `PlanProductParams{ID}` It fails, `product[name] is missing`
3. try to create a new plan for this product. Provide also a name `PlanProductParams{ID, Name}` It fails, `Product already exists`

### Expected behavior

According to the spec https://stripe.com/docs/api/plans/create The `PlanProductParams` should serialize as a string ID. Instead it serializes as an object, it tries to recreate an existing product and fails.

### Code snippets

```Go
params := &stripe.PlanParams{
    AmountDecimal:  stripe.Float64(amount),
    Interval:       stripe.String(string(stripe.PlanIntervalMonth)),
    Product:        &stripe.PlanProductParams{ID: stripe.String(productID)},
    Currency:       stripe.String(string(stripe.CurrencyUSD)),
    Nickname:       stripe.String(nickName),
    UsageType:      stripe.String(string(stripe.PlanUsageTypeMetered)),
    AggregateUsage: stripe.String(string(stripe.PlanAggregateUsageSum)),
}
plan, err := stripeClient.API.Plans.New(params)
assert.NotNil(err)
```

### OS

Debian 11

### Go version

go 1.24.1

### stripe-go version

v.76.6.0

### API version

2023-10-16

**Comment by remi-stripe** [comment]
@anastasop Sorry for the trouble on this one. The way you're using the API lets you create a Plan and a brand new Product at the same time while setting/forcing it's id. That's why the request is rejected because you already have a product with that id. 
Instead, the API expects you to pass `product: 'prod_123'` as a string. Looking at the library, it looks like we mistakenly removed support for this feature last year [here](https://github.com/stripe/stripe-go/pull/1512/files#diff-11ffedf6a81044546aa19c8009998208f5a7afec3cdff04ca4281117b5ec0da7R165) which is a bug we'll need to fix.

In the meantime, you can use `AddExtra` like this:
```
params := &stripe.PlanParams{
    AmountDecimal:  stripe.Float64(amount),
    Interval:       stripe.String(string(stripe.PlanIntervalMonth)),
    Currency:       stripe.String(string(stripe.CurrencyUSD)),
    Nickname:       stripe.String(nickName),
    UsageType:      stripe.String(string(stripe.PlanUsageTypeMetered)),
    AggregateUsage: stripe.String(string(stripe.PlanAggregateUsageSum)),
}
params.AddExtra("product", "prod_123")
plan, err := stripeClient.API.Plans.New(params)
assert.NotNil(err)
```

Note that the Plan API has been replaced by the Price API over 3 years ago and I would highly recommend switching to it instead. You can read more about it here: https://stripe.com/docs/products-prices/how-products-and-prices-work

**Comment by anastasop** [comment]
Fixed. Thank you.
