### ISSUE TITLE
Update payment intent parameters are not correct

### ISSUE THREAD

**Issue by zepatrik** [stripe/stripe-go#1845]
### Describe the bug

The parameters struct has `mandate_data` and `confirm` fields, but they are not supported on the update endpoint. There are probably more such fields.

### To Reproduce

```go
pi, err := stripeClient.PaymentIntents.Update(piID, &stripe.PaymentIntentParams{
	Confirm: Ptr(true),
	MandateData: &stripe.PaymentIntentMandateDataParams{
		CustomerAcceptance: &stripe.PaymentIntentMandateDataCustomerAcceptanceParams{
			AcceptedAt: Ptr(time.Now().Unix()),
		},
	},
})
```
compiles, but returns a 400 error.

### Expected behavior

The SDK has the correct parameters for each endpoint.

### OS

macos

### Go version

go1.22.1

### stripe-go version

v76.24.0

### API version

2023-10-16

**Comment by remi-stripe** [comment]
@zepatrik the stripe-go SDK unifies parameters for Create and Update at the moment which prevents us from supporting cases where a parameter is only allowed on Create or Update but not the other one. This is currently by design unfortunately and not something we can fix without forcing a rename and duplication of all those types where 99.9% of the content is identical.
The best approach here is to refer to the official API Reference to see what is supported on Update.

**Comment by zepatrik** [comment]
It would at least help to have it in the godoc string of the parameters where it applies, as it is super confusing when you get a "bad request" error from a payload that looks completely fine.

**Comment by remi-stripe** [comment]
Yeah it's something we'd like to support in the future for sure, but not planned in the medium term at least, but I'll keep track of the ask!
