### ISSUE TITLE
Support passing key when create client

### ISSUE THREAD

**Issue by zjc17** [stripe/stripe-go#1863]
### Is your feature request related to a problem? Please describe.

I need to use multiple stripe client in one project.

But currently, the `stripe.Key` is a global variable shared in the same project

### Describe the solution you'd like

Current code
```golang
func getC() Client {
	return Client{stripe.GetBackend(stripe.APIBackend), stripe.Key}
}
```
Adding this function after every `func getC() Client `
```golang
func GetC(key string) Client {
	return Client{stripe.GetBackend(stripe.APIBackend), key}
}
```

**Comment by zjc17** [comment]
Current work around:

From 
```golang
result, err := session.New(params)
```
To
```golang
result, err = session.Client{
B:   stripe.GetBackend(stripe.APIBackend),
Key: "sk-xxx",
}.New(params)
```

**Comment by anniel-stripe** [comment]
Hi there! Looks like you found a solution, but we support setting API keys per-request using 

```go
sc := &client.API{}
sc.Init("sk_test_...", nil)
sc.Charges.Get(...)
```

as indicated in the Stripe docs under https://docs.stripe.com/api/authentication?lang=go (see the "Per-request API Key" example). I'm going to mark this issue as resolved since the above example seems to resolve the issue at hand.
