### ISSUE TITLE
cancel subscription response no such subscription

### ISSUE THREAD

**Issue by samygou** [stripe/stripe-go#1887]
### Describe the bug

When I cancel a subscription, has a error: no such subscription
version: v79.2.0

### To Reproduce

![Snipaste_2024-07-11_14-22-54](https://github.com/stripe/stripe-go/assets/44772973/902c685f-bfb2-4049-81e3-e299c94653ba)

### Expected behavior

When I query the subscription, I can find the corresponding subscription, but when I cancel the subscription, I get the error: no such subscription.

### OS

windows11

### Go version

Go1.22.5

### stripe-go version

v79.2.0

### API version

2024-06-20

**Comment by samygou** [comment]
version: v79.1.0

**Comment by remi-stripe** [comment]
@samygou This looks like an integration support question and is better directed to our support team instead: https://support.stripe.com/contact

To unblock you though, the Subscription looks already canceled since in your screenshot it has `Status:canceled`. This is akin to being deleted already and so when you try to cancel it again it says the Subscription doesn't exist anymore. The error message is definitely not the clearest but it's all expected behavior. If you have follow up questions, please work with our support team!
