### ISSUE TITLE
Customer Metadata Search doesn't return results in first attempt

### ISSUE THREAD

**Issue by sibtaina** [stripe/stripe-go#1891]
### Describe the bug

I am creating a new Customer object which has a couple of metadata keys as part of an API. When another API tries to search that metadata key right after creation by querying it, at times I don't get the value that I am searching for and it doesn't return anything. Usually, on a second attempt, it returns the value. Is this a known issue or something I can update on my end to fix this intermittent behavior?

### To Reproduce

1. Create Stripe Customer with Metadata key values using `customer.New` in one API
2. Fetch the Metadata key using `customer.Search` in another API 
3. The value of the Metadata key is returned intermittently, sometimes it returns on first attempt and sometimes it return on second attempt.

### Expected behavior

Return the value of Metadata key on first attempt as it is a critical part of our business logic.

### Code snippets

```Go
// Stripe create customer
func stripeCreateCustomer(userPayload *users.UsersCreatePayload, emailVerificationToken string) (result *stripe.Customer, err error) {
	params := &stripe.CustomerParams{}
	params.Email = &userPayload.Email
	params.Name = &userPayload.CompanyName
	params.Phone = &userPayload.Phone
	params.PaymentMethod = &userPayload.PaymentMethodID
	params.AddMetadata(MetadataFullNameKey, userPayload.Name)
	params.AddMetadata(MetadataTokenKey, emailVerificationToken)
	params.AddMetadata(MetadataVerifiedFlagKey, "false")
	params.InvoiceSettings = &stripe.CustomerInvoiceSettingsParams{
		DefaultPaymentMethod: &userPayload.PaymentMethodID,
	}

	result, err = customer.New(params)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Stripe search customer by token
func stripeSearchCustomerByToken(token string) *customer.SearchIter {
	params := &stripe.CustomerSearchParams{
		SearchParams: stripe.SearchParams{
			Query: fmt.Sprintf("metadata[%q]:%q", MetadataTokenKey, token),
		},
	}
	result := customer.Search(params)
	return result
}

// call search token
func searchTokenWrapper(token string) {

	customer := stripeSearchCustomerByToken(token)

	if len(customer.CustomerSearchResult().Data) > 0 {

		// customer token exists

	} else {

		// customer token doesn't exist

	}
}
```

### OS

Linux

### Go version

1.20.14

### stripe-go version

v78.6.0

### API version

2024-05-09

**Comment by remi-stripe** [comment]
@sibtaina Github issues are limited to bugs and feature requests with the SDK itself. This is more an integration support question about our API which is better directed at our support team: https://support.stripe.com/contact

To unblock you though I can confirm that this is expected behaviour on our end. The Search API is not real time and we cover it in the docs [here](https://docs.stripe.com/search#data-freshness). It's powered by a completely different system than our usual APIs which allows us to do fuzzy matches and more complex criteria and it comes with a delay in syncing the data. If your different systems need the info in real time then the best option will be to cache the data on your end in your database instead.
