### ISSUE TITLE
How to use vendoring when nested packages references tip?

### ISSUE THREAD

**Issue by dvdplm** [stripe/stripe-go#209]
This might be a dumb question, but how is vendoring supposed to work with this package, where the nested subpackages all reference the full github package URL?

Example: https://github.com/stripe/stripe-go/blob/master/customer/client.go#L8

Simply having `vendor/stripe/stripe-go/` checked out at the tag we want to use does not work of course – type mismatches – so how is it supposed to work? What are we missing?

Thanks!

**Comment by brandur** [comment]
Hey @dvdplm,

> This might be a dumb question, but how is vendoring supposed to work with this package, where the nested subpackages all reference the full github package URL?

Go's packaging and import system is pretty unusual, and most of its docs don't do a good job of explaining the idea, but in idiomatic Go, all non-core import paths should be referenced by full URLs at all times. Unfortunately, this has largely required that certain tricks be used to get vendoring working.

By far your best and easiest option is to have everyone upgrade to Go 1.6 to gain access to its [special vendor directory feature](https://blog.golang.org/go1.6). What this does is essentially add a directory called `vendor` as a package search path in addition to the normal `$GOPATH/src`. It's simplified a lot of things in the world of Go dependency management and is unquestionably the way forward, so I'd suggest upgrading and moving to it sooner rather than later.

In previous versions of Go, generally a tool like [Godep](https://github.com/tools/godep) was generally used to achieve a similar result. Running `godep save` would have Godep pull dependencies in a local directory of its own format. Of course you're still left with the absolute URL problem, so what you'd do is replace all Go commands with Godep commands so that it will perform some environment replacement magic to have dependencies found correctly (i.e. `godep go build` instead of `go build` or `godep go install` instead of `go install`).

Despite the addition of `vendor` in 1.6, Godep is still useful today in that it will do the vendoring for you. If you run `godep save` on 1.6, its behavior will change so that instead of building an index in its own format, it will create a `vendor` directory and put all the right things in it.

So just in summary, the suggestion here is to (1) upgrade to Go 1.6, and (2) run `godep save`.

I'm closing this issue out, but let us know if you have any other problems.

**Comment by dvdplm** [comment]
@brandur thank you very much for your detailed response.

We are indeed on Go 1.6 and will most probably switch to vendoring in the coming days.

I wonder however about your statement on import paths using full URLs for nested packages. I tried to find references to this in the official docs and around the net and can't find any (I'm probably a lousy googler). I do find others with similar problems http://stackoverflow.com/questions/14323872/using-forked-package-import-in-go and "creative" solutions such as the "fake PR trick": http://blog.campoy.cat/2014/03/github-and-go-forking-pull-requests-and.html

I would love to understand the reason for having full URLs for nested packages. I fail to see the benefit to be honest, so any light you can shed on that would be very much appreciated.

Do you know if stripe-go works using something like `gopkg.in/stripe/stripe-go.v7`? I bet it's broken for the same reason right?

**Comment by brandur** [comment]
Hey @dvdplm, just to make sure that I'm understanding you correctly, when you speak of "full URLs in nested packages", you're talking about how for example the "card" package [will reference the Stripe package as its full path right](https://github.com/stripe/stripe-go/blob/ef09e90591579eefe99b56400061a85f7cac3641/card/client.go#L10)?

Could you talk a little bit about the problem you're running into exactly? I may be able to suggest something.

> I wonder however about your statement on import paths using full URLs for nested packages. I tried to find references to this in the official docs and around the net and can't find any (I'm probably a lousy googler).

I don't think they ever talk about "full URLs", but if you [start at the section on import paths](https://golang.org/doc/code.html#ImportPaths) and read through, you'll see that they do describe this technique, even if not explicitly.

I think it's worth nothing that Go makes absolutely no distinction between packages and "subpackages". When "github.com/stripe-go/card" references "github.com/stripe-go", it's the same as if the latter was referenced from "github.com/me/myproject". In both cases, Go uses exactly the same technique to find to find the target: it starts at either `$GOPATH/src` or `./vendor` and iterates down.

> I do find others with similar problems http://stackoverflow.com/questions/14323872/using-forked-package-import-in-go and "creative" solutions such as the "fake PR trick": http://blog.campoy.cat/2014/03/github-and-go-forking-pull-requests-and.html

These talk about contributing to open-source projects with pre-baked import paths by adding your fork as a Git remote at their normal paths instead of trying to `go get` the fork. This is definitely the right way to handle that situation.

> Do you know if stripe-go works using something like gopkg.in/stripe/stripe-go.v7? I bet it's broken for the same reason right?

We don't recommend the use of gopkg.in right now, and indeed it's broken because a project needs to be specially reworked when it has subpackages (the import paths need to be changed to gopkg.in even on master). [See this gopkg.in issue for more information on that point.](https://github.com/niemeyer/gopkg/issues/9)

**Comment by dvdplm** [comment]
> you're talking about how for example the "card" package will reference the Stripe package as its full path right?

Correct. :)

The problem – and I'm not sure there is one tbh – is that we're having trouble pinning down the stripe-go version we're running. The real fix, as you point out both here and the docs, is vendoring. What I was getting at was: 

  1. understand the reasoning behind using full-URL imports like you do and 
  2. have a quick&easy fix for our versioning problem, using `gopkg.in` without having to fork the lib

> …adding your fork as a Git remote…This is definitely the right way to handle that situation.

Agreed, which is why it'd feel pretty awkward to apply here: we're not trying to contribute so forking and PR'ing seems like unnecessary ceremony (not saying we will not contribute, and when we do, that's how we'd do it!).

> We don't recommend the use of gopkg.in right now

That's good to know and something perhaps worth mentioning in the docs? If I'm understanding you correctly your recommended way of dealing with versioning is primarily through Go 1.5/1.6 style vendoring and/or using godeps et alii.

I guess my only remaining question/curiosity remains understanding the benefit of using `stripe "github.com/stripe/stripe-go"` vs `stripe "stripe/stripe-go"` but I don't want to waste your time any more.

Again, thanks for your help! :)

**Comment by brandur** [comment]
> That's good to know and something perhaps worth mentioning in the docs? If I'm understanding you correctly your recommended way of dealing with versioning is primarily through Go 1.5/1.6 style vendoring and/or using godeps et alii.

Cool! This whole Go import thing is kind of weird, but the basic answer here is that a user shouldn't be using a gopkg.in path unless the package itself recommends its use, so by recommending installation of `go get github.com/stripe/stripe-go`, we're also implicitly not recommending gopkg.in.

That said, I think for any package that doesn't have any subpackages, you might be able to get away with using gopkg.in anyway, but you'll run into trouble if you try to use it with Stripe.

> I guess my only remaining question/curiosity remains understanding the benefit of using stripe "github.com/stripe/stripe-go" vs stripe "stripe/stripe-go" but I don't want to waste your time any more.

I tend to agree that having some sort of relative import mechanism would be nice, but have been superseded by the language here :)

If you try to use dependencies with relative import paths in other projects, you'll start to see errors like `local import "XXX" in non-local package` because the compiler itself doesn't allow this. [This Stack Overflow answer breaks that down well](https://stackoverflow.com/questions/10687627/relative-import-from-parent-directory), and make sure to also see the related [golang-nuts mailing list discussion](https://groups.google.com/d/msg/golang-nuts/1XqcS8DuaNc/Lq5OhTCuKMcJ) and [language issue that introduced the behavior](https://codereview.appspot.com/5787055).

I feel like I'm failing to explain this clearly, but the summary again is that: although the Go compiler will allow relative import paths in some cases, its specifically designed so that in general only absolute paths rooted at `$GOROOT/src` or `./vendor` will work in the more general case.
