### ISSUE TITLE
A way to convert lists into iters

### ISSUE THREAD

**Issue by dominicbarnes** [stripe/stripe-go#219]
I have a specific use-case in mind, but this is also a more general question as well. (it may already be possible, but it isn't clear)

Say I get a customer and I want to iterate all their subscriptions. I could rely on the `SubList` already present, but it's possible there could be further items that aren't on that first page. Is there a way to convert something like `Customer.Subs` into an `Iter` fairly easily?

```go
i := customer.Subs.ToIter()
for i.Next() {
  // handle sub
}
```

My current way of iterating the subs looks like:

```go
for _, sub := range customer.Subs.Values {
  // handle sub
}
// page 2+ are not included here though
```

This same question applies to any other sub-resource list. (eg: `Invoice.Lines`)

**Comment by brandur** [comment]
> I have a specific use-case in mind, but this is also a more general question as well. (it may already be possible, but it isn't clear)

I think it's mostly manual today :/ For example:

``` go
allSubs := cus.Subs().Values
if len(allSubs) > 0 {
i := subs.List(&SubListParams{Start: allSubs[len(allSubs)-1], Customer: cus.ID})
if i.Next() {
    allSubs = append(allSubs, i.Current())
}
for _, sub := range allSubs {
    ...
}
```

And given how ugly that is, it might be better just to eat the extra API call:

``` go
i := subs.List(&SubListParams{Customer: cus.ID})
if i.Next() {
    sub := i.Current()
    ...
}
```

A little less efficient, but the code sure looks a lot better.

I [wrote up a small demonstration branch here](https://github.com/stripe/stripe-go/compare/master...brandur-seeded-iter) to spec out a more automated method. An example usage:

``` go
    cus := customer.Get(...)
    i := customer.SubsIter(cus)
    for i.Next() {
        sub := i.Current()
        ...
    }
```

TBH though, I don't think it makes use _that much easier_ and does add quite a bit of boilerplate, so I'd be tempted to just recommend one of the approaches above rather than add it in. Thinking about it a little more, I think that a better approach would have been to inject a seed list value directly into `SubListParams` and then pass it through right into the iterator, but I'm not sure that I'll spend the time assembling that prototype.

**Comment by brandur** [comment]
I'm closing this one out for now, but let me know if you have any thoughts here!
