### ISSUE TITLE
Unrecognized request URL (POST: /v1/customers//subscriptions)

### ISSUE THREAD

**Issue by tj** [stripe/stripe-go#223]
Hello, I'm getting this error when trying to create a subscription. I just grabbed the pkg today so it's up to date. I'll tweak locally for now. Log from the client:

```
2016/04/13 15:47:19 Requesting POST api.stripe.com/v1/customers//subscriptions
```

I'm assuming other end-points may have the same issue.

**Comment by tj** [comment]
derp, ignore me

**Comment by brandur** [comment]
We could probably use a few extra validations here :/ Let us know if anything else comes up.

**Comment by tj** [comment]
Did this again hahaha. It looked more confusing for customers because you get `/v1/customers` in the errors which looks legit

**Comment by brandur** [comment]
@tj One somewhat positive recent development here is that subscriptions are now a top-level resource (see #224 for more details). Although not a fix per se, if you update to the latest code on this package, the omission of a customer should now give you a better error because it now goes in as a parameter instead of a component in the URI.
