### ISSUE TITLE
Expose planList (and possibly other similar types)

### ISSUE THREAD

**Issue by dominicbarnes** [stripe/stripe-go#227]
I recently tried to do a mock of the `GET /plans` endpoint. However, when I tried to inject my own fixture data, I ran into trouble because the `planList` type that is being used to handle that response is private.

Is there any reason that [planList](https://github.com/stripe/stripe-go/blob/9492eb6d10c700ce855dcf94dfeee6c80798bd3c/plan/client.go#L131-L134) is declared this way and is also private? Can this just be made into a public `PlanList` type? (similar to `SubList` and others)

As it stands now, I need to rely on an external fixture file that I read and pass to `json.Unmarshal`, but I'd prefer to use a raw value directly in my tests to keep them more self-contained.

**Comment by brandur** [comment]
I suspect that it was made internal like that to reduce the number of types being exported, and any inconvenience that the decision caused was never noticed because a sane testing strategy was never implemented for the package (i.e. it just does live API calls).

I think we could expose it, but we'd have to go through and do it for every type, which would be a pretty major change.

Did you consider trying to mock out `Iter` instead? It looks like this still might be slightly problematic because the `values` field on it is internal, but we could add a new initialization function specifically for testing. I think this would be more symmetric with what you're doing for non-list functions too because it's an `Iter` that's actually being returned from the list methods.

**Comment by dominicbarnes** [comment]
Unfortunately, I don't think mocking `Iter` helps in my case, since I'm using a mock "backend", which only deals with the raw HTTP requests.

**Comment by brandur** [comment]
> Unfortunately, I don't think mocking Iter helps in my case, since I'm using a mock "backend", which only deals with the raw HTTP requests.

Ah, I see!

Alright, since as you pointed out, it appears to be completely haphazard as to which of these list structs are internal and which are not, it seems fine to me to make `plan.planList` into `stripe.PlanList`, especially given that it's not a breaking change because we're only exposing it through an iterator.

Issued a patch in #228.

**Comment by dominicbarnes** [comment]
Thank you *very* much! I appreciate it :)

**Comment by brandur** [comment]
> Thank you very much! I appreciate it :)

No worries at all! Released as 13.10.0.

**Comment by dominicbarnes** [comment]
@brandur it looks like I will need the same treatment applied to `/invoices` as well. That's just me, but I'm noticing a lot of other cases that are exactly the same, such as `/events`.

Should I open a new issue for all those remaining cases? (I can do a quick audit if you'd like, and even PR if that's all right)

**Comment by brandur** [comment]
> Should I open a new issue for all those remaining cases? (I can do a quick audit if you'd like, and even PR if that's all right)

@dominicbarnes Looks like you got it already. Thanks for taking the initiative here!
