### ISSUE TITLE
Old version

### ISSUE THREAD

**Issue by pjebs** [stripe/stripe-go#235]
I am using this Library and when I go on the documentation website (which dynamically changes to my credentials), it says I am using the old API.

**Comment by pjebs** [comment]
"You are using an older version of the API. Learn more about API versions"

**Comment by remistr** [comment]
@pjebs: Whenever we release backwards-incompatible changes, we release it behind a new API version. This allows us to push changes without impacting existing integrations that expect the code to run another way. Each API version is documented here: https://stripe.com/docs/upgrades

This message is simply here to tell you that you're currently on an older API version so part of the documentation won't be correct for you because of that. Separately, since you're using the Go bindings, the library will always use a specific API version that it's been tested against.

The bindings are currently forcing the API version 2016-03-07 as you can see [here](https://github.com/stripe/stripe-go/blob/8e51de3a37356b38020e19f2dc6dab39b88ca9b2/stripe.go#L24)
