### ISSUE TITLE
Why return Iter instead of type?

### ISSUE THREAD

**Issue by rodzzlessa24** [stripe/stripe-go#292]
First of all thank you for this API it has been great to work with. One thing though that I don't yet see the benefit is returning an `Iter` type for list queries. For example getting a list of charges we need to do this:

```go
i := charge.List(params)
for i.Next() {
    charge := i.Charge()
}

if err := i.Err(); err != nil {
    // handle
}
```
`i.Charge() ` Just returns a pointer to a `Charge` type. Which then if I wanted to get a slice of all the charges I would have to do this:

```go
var cs  []*stripe.Charge

i := charge.List(params)
for i.Next() {
    cs = append(cs, i.Charge())
}

if err := i.Err(); err != nil {
    // handle
}
```

Which feels a bit messy to me. I think much cleaner would be something like this

```go
cs, err := charge.List(params) // returns ([]*stripe.Charge, error)
if err != nil {
  // Handle err
}
```
I know I'm missing something here so what is the benefit of using the Iter type?

**Comment by brandur** [comment]
Hey @rodzzlessa24, definitely a worthwhile question.

The reason that we return the iterator is because of the [API's pagination on list endpoints](https://stripe.com/docs/api/go#pagination).

Returning a raw slice of charges would mean that the bindings would have to iterate through every possible page on an endpoint before they could give you an answer, and that could be incredibly expensive if you have a lot of objects and therefore have to make a lot of HTTP calls.

The iterator is designed to strike a compromise by giving you finer-grained control if you need it, but also abstracts away the pages themselves so that each object can be handled in a separate loop.

If you're sure that you don't need to worry that much about the number of objects that will be returned, or if the time it takes to return isn't too important, it should be quite easy to abstract away the iterator with your own helper function with the signature that you described.

I'm going to close this issue out, but let me know if you have any other questions about it!
