### ISSUE TITLE
Retry iterator request?

### ISSUE THREAD

**Issue by tejasmanohar** [stripe/stripe-go#300]
If an iterator request fails, how would we handle retries? I guess we need to grab the last ID from `Current` and manually fill in the `starting_after` param? Seems like there could be a nice retry or simpler, request() function on the iterator.

**Comment by tejasmanohar** [comment]
Or maybe more properties here- https://github.com/stripe/stripe-go/blob/master/iter.go#L18-L26 - could be exposed so that you can rebuild the request on `iter.Err() != nil { ... }`?

**Comment by brandur** [comment]
Given that the iterator is a bit of a black box already (in that it's opaque to the user when a new page fetch will happen), my vote would be to implement some sort of automated retry policy within it. We'd want reasonable defaults, but would probably allow some configuration (the Ruby gem does something similar already).

It doesn't seem too bad to expose `ListParams` from within `Iter` either. Although we'd probably want to do it via a function (`GetListParams`) so that the iterator itself couldn't be modified by a user.

**Comment by tejasmanohar** [comment]
+1 for customizable retries in iterator with sane defaults AND exposing `GetListParams`

**Comment by brandur** [comment]
Cool! I have to say that unfortunately we're unlikely to get this picked off in the short term, but I'm happy to support any such endeavors. For now I'm tagging this as "future".

**Comment by tejasmanohar** [comment]
@brandur What do you think about just allowing users of this library to override / provide their own HTTP client? That seems like the go-esque way to do it. If customers want to retry on a specific error, that's easily achievable via a custom [transport](https://github.com/f2prateek/train).. same with rate limits (https://github.com/stripe/stripe-go/issues/306).

**Comment by tejasmanohar** [comment]
Looks like I can already do that (https://github.com/stripe/stripe-go/blob/master/stripe.go#L100) perfect! In that case, I think I'll close out this issue since it solves my use case... but feel free to re-open or make a new one if you think it's something the library should support

**Comment by tejasmanohar** [comment]
To expand, my reasoning is people may always want different retry policies, backoff periods, etc. dependent on their application. Same with rate limits. Better not to have to maintain that in the lib
