### ISSUE TITLE
Empty ZipCheck parameter when Zip wasn't provided

### ISSUE THREAD

**Issue by hexdigest** [stripe/stripe-go#304]
Hi, 

Comment in the library stands for:
```
// Verification is the list of allowed verification responses.
// Allowed values are "pass", "fail", "unchecked", "unavailabe".
type Verification string
```
Which is not true when you don't submit Zip when requesting token via mobile SDK. In such case ZipCheck is empty string.

Can you please advise?
Thanks!

**Comment by remistr** [comment]
@hexdigest This is expected behaviour since `address_zip_check` in our API can also be null. I agree that the wording could explicitly mention that the string can be empty but it doesn't say it can't, it just gives you the values the string _can_ take.

Our documentation around `address_zip_check` in the API [here](https://stripe.com/docs/api/curl#account_card_object-address_zip_check) says

> If address_zip was provided, results of the check: pass, fail, unavailable, or unchecked.
