### ISSUE TITLE
set client api version?

### ISSUE THREAD

**Issue by tejasmanohar** [stripe/stripe-go#327]
is there an option for that?

**Comment by remistr** [comment]
@tejasmanohar The Go library doesn't support setting your own API version. The reason is that we already force a specific API version in the bindings and that's the only one supported. This is documented in more details in our [readme](https://github.com/stripe/stripe-go/blob/a5c22801047884b9baa86f8e124b90a817381494/README.md#versioning).

**Comment by brandur** [comment]
Yeah, the basic idea here is that while dynamic languages can easily reprogram themselves to adapt for the addition or removal of fields across API versions (and even while the client library version stays the same), because static languages have each field already predefined, they're much more suited to only a single API version.

Instead of upgrading API version from the Dashboard, you instead upgrade by upgrading your client bindings. This has the advantage of allowing the compiler to warn you about problems that you might encounter during the upgrade (say if a field was removed for example).

**Comment by tejasmanohar** [comment]
makes sense. i agree with this logic

**Comment by tejasmanohar** [comment]
though it does make it impossible to make a specific API call w/ one version afaict
