### ISSUE TITLE
json: cannot unmarshal string into Go value of type stripe.EventRequest

### ISSUE THREAD

**Issue by ronpastore** [stripe/stripe-go#431]
Hi, 
apologies if i'm missing something. I'm using the latest version, V24 for stripe-go, and set my test webhook to the latest version on Stripe, 2017-06-05, but getting a failure when unmarshalling events in my web hook, "json: cannot unmarshal string into Go value of type stripe.EventRequest".  if i unmarshall into a map[string]interface{}, "request" is a string, but looking at the struct here it's expecting something more i believe, https://github.com/stripe/stripe-go/blob/master/event.go#L22

Go version is 1.7.1, i also am able to confirm webhook data is set to stripe version 2017-06-05 (latest).

Code looks like:

var event stripe.Event
if err := json.NewDecoder(r.Body).Decode(&event); err != nil {
  panic(err)
}

**Comment by remi-stripe** [comment]
@ronpastore would you be able to give me a bit more details? The latest API version should send a hash instead of just a string for the request id. Are you using the "Send test webhook" button or generating a real event in your account? If the latter, do you have an event id you could share so that I can check?

**Comment by ronpastore** [comment]
sure, thanks so much!  I'm using a real event, not the Send Test Webhook button, here's a recent event id: evt_1AfXThJJNeKrZOzbjJekxkAg

if i decode it to a map[string]interface, the two fields in question are:

(string) (len=11) "api_version": (string) (len=10) "2017-06-05"
(string) (len=7) "request": (string) (len=18) "req_B1afu1dM3saEiW"

**Comment by ronpastore** [comment]
but worth noting this account overall is using API version 2017-04-06, i'm hoping to upgrade to latest.

**Comment by remi-stripe** [comment]
@ronpastore Thanks for the extra details. The issue seems to be with the way the event is formatted on your Test webhook endpoint. In both cases we send `"request": "req_B1afu1dM3saEiW",` instead of sending this as a hash.

I'd recommend sending an email to our support team so that they can investigate as the event should be formatted properly in that case. You can contact them [here](https://support.stripe.com/email).

Otherwise, if you open a separate account just for testing, this account would be on the latest version and you should see the event formatted as expected. It looks like a bug in the feature that allows you to get Test events with a different API version.

**Comment by ronpastore** [comment]
thanks @remi-stripe. will do. i think we're all good on our end, we actually have multiple Stripe accounts supported by the same code base, and one of the more recent ones is on the latest API and working as expected, so we should be able to upgrade them all. nonetheless, i'll let Stripe know about the test webhook issue. thanks again!
