### ISSUE TITLE
Event.UserID field from older API versions isn't supported

### ISSUE THREAD

**Issue by nbosscher** [stripe/stripe-go#493]
According to stripe's [backwards compatibility doc](https://stripe.com/docs/upgrades), shouldn't that field be retained? 

It was removed in 0a8d6889ac3a1d0dbdb6d4958fb06d6345fd5e98

**Comment by brandur-stripe** [comment]
> According to stripe's backwards compatibility doc, shouldn't that field be retained?

Yes, we usually do retain them.

The reason that we pulled it out of Go is that unlike our other libraries, Go locks itself to one particular API version by sending an explicit `Stripe-Version` header when making API requests so even an account locked to an old API version will instead get the version that's built into their copy of stripe-go. We find that this model maps to Go's strong typing much more cleanly.

Do you ask because of webhook receipt?

**Comment by nbosscher** [comment]
Yes, I'm trying to decode a webhook request. I have to parse for several accounts on different versions.
 
However, my issue has been solved by getting approval to migrate all the accounts to the latest api-version. Feel free to close

**Comment by brandur-stripe** [comment]
> However, my issue has been solved by getting approval to migrate all the accounts to the latest api-version. Feel free to close

Ah, that's great to hear.

I don't think adding `UserID` back would be the worst thing given that there is a legitimate use case in webhooks, but I'd prefer not to unless someone really needs it. Thanks.
