### ISSUE TITLE
ConstructEvent with injectable clock

### ISSUE THREAD

**Issue by jmhodges** [stripe/stripe-go#498]
I use fake clocks everywhere in my code to allow myself deterministic tests that don't fail because of time changes, or logic races, etc. ConstructEvent and its peers all use a hardcoded `time.Since` that doesn't allow for that. It would be nice if it did.

(If you're not familiar with clocks for testing, you can find the one I wrote at https://github.com/jmhodges/clock)

**Comment by ob-stripe** [comment]
Hey @jmhodges. While I'm not the one who wrote the Go implementation of the signature verification code, I wrote the implementation in most other languages. Using dependency injection to inject a clock object is something I considered. I eventually decided against it to keep the implementations lean and because there didn't seem to be much practical use for it (though I agree that having tests for time-dependent code use real clocks is not very good practice).

I'll defer to @brandur-stripe here as he's the one who wrote the Go implementation and is more familiar than I with Go's best practices.

**Comment by brandur-stripe** [comment]
Hm, yeah this seems to be a good idea. Given that I don't think there's anything like a clock interface in the standard library, I might suggest that alternatively we just inject a `now` value.

Looking at the current APIs though, we already have `ConstructEvent`, `ConstructEventWithTolerance`, and `ConstructEventIgnoringTolerance` and adding a new value would bring in yet another dimension of parameter, so I think we might have to introduce a version of `ConstructEvent` that takes an `*Options` struct. We could possibly include a `time.Time` pointer there with a `nil` indicating to "use current time" so that this would remain the default.

**Comment by ob-stripe** [comment]
Closing due to age. We might reopen if there's more demand for this.
