### ISSUE TITLE
CustomerParams doesn't include `PayImmediately` bool

### ISSUE THREAD

**Issue by timendez** [stripe/stripe-go#510]
Using go @ 1.8.3 darwin/amd64 with stripe-go @ 28.6.1

The [create customer docs](https://stripe.com/docs/api#create_customer) show `pay_immediately`. I've contacted Stripe support as it's a gated parameter and had it unlocked for my account. However, I still need to send it to Stripe. Since Go is a strongly typed language, I can't just include it in the payload.

Let me know if this is something that you guys intentionally left out.

Thanks!

**Comment by timendez** [comment]
I was just told that since `pay_immediately` is a gated parameter, it doesn't show up for anyone else who isn't using Avalara integration, closing issue and editing the source locally myself.

**Comment by jsignanini** [comment]
I understand that the parameter is gated but I don't see a reason why it should not be part of this library as long as it is properly documented.

**Comment by remi-stripe** [comment]
@jsignanini There are gated parameters that we want to maintain (or even ship publicly) which we add to the library but others that have been deprecated for a long time (2+ years in this case) that we do not want to ship publicly because it increases the number of people using it.

Our Go library supports adding extra parameters to your request though for cases like this one. This is done by using the `AddExtra` method that works on all parameters struct. It would look like this:

```
params := &stripe.SubscriptionParams{
  Customer: stripe.String("cus_123"),
  Items: []*stripe.SubscriptionItemsParams{
    {
      Plan: stripe.String("pl_123"),
    },
  },
}
params.AddExtra("pay_immediately", "false")
s, err := sub.New(params)
```

**Comment by jsignanini** [comment]
@remi-stripe that makes sense, thanks for the explanation!

**Comment by timendez** [comment]
@remi-stripe wow that's so neat! I didn't know about that at the time
