### ISSUE TITLE
Invalid POST parameter for creating card

### ISSUE THREAD

**Issue by natdm** [stripe/stripe-go#523]
Upgraded from 28.6 to 29.0.1 and am getting this when I try to create a card based on a token for a customer:

```json
{
    "status": 400,
    "message": "Invalid request (check your POST parameters): unable to determine value for parameter: source. For assistance, please email support@stripe.com.",
    "request_id": "<do you need this>?",
    "type": "invalid_request_error"
}
```

I'd email the support line, but this worked a few minutes ago and does not now.

I also have the most up to date version of the API, though I believe this library enforces a specific version.

Code:

```go

// CreateCard creates a card for Stripe.
// takes the stripe customer ID, and the token.
func (b *Billing) CreateCard(cus, tok string, def bool) (*stripe.Card, error) {
	params := stripe.CardParams{Customer: cus, Token: tok, Default: def}
	return card.New(&params)
}

```

Called with correct values for customer, token. Default is set to true.

**Comment by natdm** [comment]
Oh.. wondering if I should be using this somehow?
```go
func (c *CardParams) AppendToAsCardSourceOrExternalAccount(body *form.Values, keyParts []string)
```

**Comment by remi-stripe** [comment]
@natdm your code should look like this:
```
    t, err := token.New(&stripe.TokenParams{
        Card: &stripe.CardParams{
            Token: "card_1234",
        },
        Customer: "cus_1234",
        Params: stripe.Params{Account: "acct_1234"},
    })
```
I've confirmed this works on my end with the latest version (29.0.1).

**Comment by natdm** [comment]
@remi-stripe 

I'm creating a new card based on a token from stripe.js, not a token based on a card. I'm hoping to get back a `*stripe.Card`, is this not possible?

Following this API: https://stripe.com/docs/api/go#create_card

**Comment by remi-stripe** [comment]
@natdm Oh sorry I misunderstood your question. It seems this broke unfortunately. I'll work on a fix in a PR.

**Comment by remi-stripe** [comment]
@natdm Okay I figured it out. The issue is that you pass both a value for `Token` and for `Default`. The first one is sent under `source` while the latter is sent under `source[default_for_currency]`.

This is an invalid request so the API just rejects it as expected. You should simply not pass `Default: true` in this code. The `Default` property is used for ExternalAccounts when you add a debit card to a Custom account.

It used to work because the library ignored that parameter incorrectly so you were lucky. But it does not anymore which is why you get this error.

Setting a card as the default source happens separately by calling the Update Customer [API](https://stripe.com/docs/api#update_customer) after the fact and passing the `default_source` parameter as `card_XXXX`. You can also just use the same API and pass `Source: "tok_XXXX"` which would delete the old default source and put the new one in its place.

**Comment by natdm** [comment]
Ah, makes sense. Thanks @remi-stripe

**Comment by remi-stripe** [comment]
@Maldris thanks for the information. Just in case you did not know: the currency of a card does not matter for charges. You don't need to set it and you can charge a card in any currency you want, even changing every day. The `currency` on the card/token is really just when you use a debit card for payouts in the US on Custom accounts.

**Comment by Maldris** [comment]
Thanks for the review, I was aware of that.

The previous developer was using the currency to apply some business logic to some of our charges and subscription behaviours. I've instead added a new enumeration to our local database that manages that logic, so this shouldn't be an issue in the future.

**Comment by shanedasilva** [comment]
I'm still seeing this issue in my application when making the following request. Any idea what I'm doing wrong? If I remove all fields except for Customer and Token the request passes. Any other card information seems to make the request params invalid.

```
params := &stripe.CardParams{
        AddressCountry: stripe.String(inputs.AddressCountry),
        AddressCity:   	  stripe.String(inputs.AddressCity),
        AddressLine1:   stripe.String(inputs.AddressLine1),
        AddressState:   stripe.String(inputs.AddressState),
        AddressZip:      stripe.String(inputs.AddressZip),
        Customer:         stripe.String(company.CustomerID),
        Name:               stripe.String(inputs.Name),
        Token:               stripe.String(inputs.Source),
}

card, err := card.New(params)
if err != nil {
	service.scope.Log().WithError(err).Error("error creating payment method on Stripe")
	return err
}
```

**Comment by remi-stripe** [comment]
@shanedasilva You are passing card details at the same time as the card token which is not supported and can not work. If you create a card from a card token (tok_123) you can not pass anything else than the `Customer` property like this:

```
params := &stripe.CardParams{
        Token:               stripe.String(inputs.Source),
}
card, err := card.New(params)
```

If you have extra information about the card such as the customer's name or billing address, this should be sent client-side while creating the card token instead of server-side. Here's a basic example with Elements: https://jsfiddle.net/ywain/5ytr8a2L/
