### ISSUE TITLE
Requests randomly fail with EOF

### ISSUE THREAD

**Issue by yns01** [stripe/stripe-go#528]
Hello,

Some of our requests fail with an EOF error:

**Logs**

I set the log level for the stripe package to the maximum value, 3. Here’s a timeline
```
"2018/02/28 21:06:24 Requesting POST api.stripe.com/v1/customers"
"2018/02/28 21:06:24 Completed in 65.481468ms"
"2018/02/28 21:06:24 Request to Stripe failed: Post https://api.stripe.com/v1/customers: EOF"
```

**go version go1.9.4 linux/amd64**
**stripe-go version = "v28.8.0"**

65ms seems way too fast to make an actual request to your servers (from EU, POST /customers takes usually more than 1s); also I could not find any request around that time on the dashboard. So I’m assuming that the request did not reach Stripe.

```
res, err := s.HTTPClient.Do(req)
if err != nil {
    if LogLevel > 0 {
        Logger.Printf("Request to Stripe failed: %v\n", err)
    }
    return err
}
```
Thanks!

**Comment by brandur-stripe** [comment]
Hi @yns01, thanks for including the extra logging information!

Given a network that's not perfectly reliable, some level of request failure is to be expected. Unless you're noticing issues on a problematically high number of requests, there probably isn't a bug here.

Some of our client libraries are built to retry requests automatically when they detect a failure that looks like it's intermittent like a timeout, socket error, or EOF, but `stripe-go` doesn't yet have this functionality. In the meantime, you might want to consider implementing your own basic wrapper to do the job. (It's relatively easy, and you can use [existing code in `stripe-ruby` as a reference](https://github.com/stripe/stripe-ruby/blob/3bc4256e2532d75e93ca744edc3dc7913aa79a86/lib/stripe/stripe_client.rb#L219-L223).

The one key thing to remember when implementing a retry scheme is that for any mutating operation, [an idempotency key must be used](https://stripe.com/docs/api#idempotent_requests). This guarantees that the operation won't be duplicated even if our server's received and processed the original (even if it looked like an error to the client).

Having a retry strategy is usually good practice for any external services that you're integrated with, and Stripe's no different. I hope we'll get to implementing one in `stripe-go` soon, and I've just opened #529 so that you'll be able to tell when we do.

**Comment by yns01** [comment]
Hey @brandur-stripe, thank you for your prompt reply.

We'll probably have some retry in place. We already use idempotency keys so we're covered there!

**Comment by brandur-stripe** [comment]
No worries!

> We'll probably have some retry in place. We already use idempotency keys so we're covered there!

Excellent :)

I'm going to close this issue for the time being, but you can track the progress of in-library retry implementation by watching #529. Thanks!
