### ISSUE TITLE
Missing OAuth Connect Functionality?

### ISSUE THREAD

**Issue by mkadin** [stripe/stripe-go#536]
Hi there!
I'm looking to complete an account connection as [described here](https://stripe.com/docs/connect/express-accounts#token-request).  I don't see this type of request included in this library, so I'm wondering:
1) If I'm just not finding it.
2) If it's intentionally left out for some reason.
3) If I've created a wonderful feature request!
Thanks

**Comment by remi-stripe** [comment]
@mkadin It's not in the library today and it's been left out mostly because most people use a third-party OAuth library for things like this. We could definitely add this to the library in the future though as we've done on some of our other libraries so I will tag this as a "future" feature!

In the meantime though you would either use a third-party library or make the raw request yourself!

**Comment by mkadin** [comment]
Ah, got it.  Thanks for taking a look.  For now, I'll just make the POST myself.

**Comment by ob-stripe** [comment]
This was actually shipped a while back, in version [61.23.0](https://github.com/stripe/stripe-go/blob/master/CHANGELOG.md#61230---2019-07-29).

**Comment by mkadin** [comment]
Awesome, thanks!
