### ISSUE TITLE
Custom Account Creation Problem

### ISSUE THREAD

**Issue by kei42** [stripe/stripe-go#590]
Hello,

I have an issue with the custom account creation, I got the following error: 

2018/06/15 12:53:05 Error encountered from Stripe: {"status":400,"message":"Invalid string id: ","param":"**_account_token_**","request_id":"req_XXXXXXXXXXX","type":"invalid_request_error"}

here: https://github.com/stripe/stripe-go/blob/master/account.go
the line 
AccountToken              *string                       `form:"account_token"`
I think the account_token parameter should be renamed token 
so it should be something like 
Token              *string                       `form:"token"`

Could you please handle it ? 
Thanks

**Comment by remi-stripe** [comment]
@kei42 You can see in the docs that this parameter is called `account_token` [here|https://stripe.com/docs/connect/account-tokens#use-token].

Can you give me a real request id `req_XXXX` so that I can double check what's causing the 400?

**Comment by remi-stripe** [comment]
@kei42 Okay looking into our logs I only see 2 failures from Go in the past 24 hours. Both send `account_token: ""` so it's expected that you would get an error.

Your code seems to have a bug where you send an empty string for the id instead of the id you retrieved from your browser. Once you fix it and send the real id `ct_XXXX` you should be all set

**Comment by kei42** [comment]
Ok thanks for your quick answer
