### ISSUE TITLE
Feature Request: Params to have `json:"some_field"` tags.

### ISSUE THREAD

**Issue by justjoeyuk** [stripe/stripe-go#654]
**Feature Request**

I have been using the stripe-go library for quite a while now and we've recently started to re-factor our code and rebuild our infrastructure. In the past, we have had the approach of:

- User fills fields on client application
- Client makes AJAX request to our server containing JSON representation of `AccountParams`
- Server manually hydrates the response into `AccountParams` for *every* field

The hydration process was in excess of 100 lines of code, just to convert a json object (that already abided by the rules) into `AccountParams`. In the stripe-go library, it seems like any Params model has `form:"field_name"` tags. This would be fine if I was making a request directly to stripe, from a form on the client.

However, we need to use the JSON approach as we perform our own validation and extra steps. This hydration process is very cumbersome and is prone to errors, especially if the `AccountParams` model changes - or any other related model. It creates a dependency I'd rather not have.

Rather than have a huge hydration function for converting json to `AccountParams`, it could very easily be done by doing:

```
bytes, err := json.Marshal(jsonConnectedAccount)
json.Unmarshal(bytes, &stripeAccountParams)
```

It seems like this could be genuinely resolved by simply duplicating the `form: "some_field"` tags for each field to include `json:"some_field"`. I feel as if it's a common scenario for someone to need to generate Params from a JSON request.

Is there any alternative to the Hydration method? If so, I'd appreciate knowing as it would solve this issue of a huge dependency that needs to be maintained by our team.

**Comment by justjoeyuk** [comment]
Just for reference, this is the current file we have for hydration to convert our JSON struct to AccountParams. https://pastebin.com/rhU2tM5x

**Comment by brandur-stripe** [comment]
Hey @justjoeyuk,

It's always interesting to hear about our users' architecture to this degree, so thanks in advance for providing these details.

I want to first off get it out of the way first that we probably won't do this — it seems like bad precedent to me to add code into stripe-go to support the implementation details of a particular user integration. Beyond just the philosophy, the problem is that there's no forcing function to make sure that the added `json` annotations would be fresh and problem-free. We wouldn't be using them and the majority of our users wouldn't be using them, so the only way to find out about a problem would be through you.

Aside from that though, are you sure that the security model of what you're building is sound? By deserializing Stripe parameter structs on your server and sending them off through Stripe, you're lending a huge amount of trust that your clients are sending only the data that they should be — as long as all clients are well-behaved, things are fine, but all it takes is one rogue adding fields that you didn't expect to be there, and those being directly transmitted to Stripe under your secret key.

In a similar vein, it seems like relying just on Stripe parameter structs might mean that you have less ability to add other fields that should be there when receiving a form payload — the most obvious example being a CSRF token.

If I was in your place, I'd probably drop the Stripe param structs between client and server and replace them with similar structs that contain only the extent of information that you ever expect the server to receive, and decorate those new structs with whatever encoding scheme you'd like to have. This will be more boilerplate, but in the long run will give you better security and more flexibility.

**Comment by justjoeyuk** [comment]
Thanks for the response @brahn-stripe !

In the example code I have given, we are restricting the fields the user can send us by only having the fields that we will be converting to the `stripe.AccountParams`. It literally contains the same fields as `stripe.AccountParams` minus some that we don't necessarily need right now.

Our client will send the data up, and if there are any malicious extra fields, it will be filtered out by the model. We will only get fields that are defined. We then simply need to convert this to `stripe.AccountParams` which is difficult because Stripe assumes an empty value is an `unset`.

That means we will have to do something like

```
if ourModel.BusinessName != nil {
    stripeParams.BusinessName = ourModel.BusinessName
}
```

otherwise it will attempt to unset that parameter and fail. I hope that gives more understanding.

**Comment by brandur-stripe** [comment]
Ah, I see! So JSON becomes kind of an intermediary format that moves from your internal structs to the official Stripe ones.

Alright, I think I'm going to have to stick with my original comment here — it's good that you have the security aspect figured out, but I don't think it's great precedent to put code into the library that's not actually used in it, and won't be used in the vast majority of installations. I'll reconsider that if another use case comes up where this would be useful.

For now, I think that what you're doing already, despite some boilerplate, isn't actually too bad of an approach. If you want to maximize safety and minimize boilerplate, it would be pretty easy to write a little subroutine using the [`reflect`](https://godoc.org/reflect) package that compares two type structs, and then copies fields from one to the other where names and types match.

Furthermore, it's even possible to optimize that implementation so that introspection is only done the first time any of these types is seen — you then store a primed decoder so that for any subsequent visits of those types you already know exactly what fields to copy. All JSON in Go is done via `reflect` already, so if you do the optimization pass, you could plausibly get it to the point where it's as fast as using `json`. Even if you don't, it's still fast enough that the time it would take to run would be trivial.

Going to close this out, but let us know if you have any other questions or comments.
