### ISSUE TITLE
Expanding a product when retrieving a plan causes JSON unmarshalling errors

### ISSUE THREAD

**Issue by majelbstoat** [stripe/stripe-go#692]
Simple repro:

```go
		p, err := plan.Get(code, &stripe.PlanParams{
			Params: stripe.Params{
				Expand: []*string{stripe.String("product")},
			},
		})
		if err != nil {
			log.Fatal(err)
		}
```

Expected outcome is that a plan is returned. Actual behaviour is:

`2018/09/11 15:23:28 json: cannot unmarshal object into Go struct field Plan.product of type string`

The following also fails for the same reason.
```go
		params := &stripe.PlanParams{}
		params.AddExpand("product")
		p, err := plan.Get(code, params)
```

Current workaround is to just make a second request, but that's kind of wasteful.

I'd submit a PR, but I'm not sure what your preferred approach to supporting both string and expanded return types is.

**Comment by majelbstoat** [comment]
(The Java SDK has `Product` for the string, and `ProductObject` for the object, which is kind of ugly, but works.)

**Comment by majelbstoat** [comment]
Ah, I think it's missing an UnMarshalJSON method. I'll take a crack at it.

**Comment by remi-stripe** [comment]
@majelbstoat Nice catch and sorry about the trouble. The solution is to replace the string by a `*Product` and it will "just work".

**Comment by majelbstoat** [comment]
ooh, neat.

**Comment by majelbstoat** [comment]
wait, no, I don't actually understand 😂. `Expand` takes a slice of string pointers: `[]*string`. `stripe.String()` takes a string. I don't see anything that will take a Product pointer for expansion 😬. Can you show a quick example?

**Comment by remi-stripe** [comment]
@majelbstoat Sorry I could have been clearer! [This line](https://github.com/stripe/stripe-go/blob/master/plan.go#L83) says:
```
	Product         string              `json:"product"`
```

This means that when you deserialize a plan we expect Product to be a string. But if you expand it it will be a hash. So instead you should have this line:
```
	Product         *Product              `json:"product"`
```

This will let stripe-go deserialize the product properly. If a string is returned we will automatically set `Product.Id` to the string value. If it's a hash we will deserialize the product automatically.

This works because the `Product` struct has a custom `UnmarshalJSON` [here](https://github.com/stripe/stripe-go/blob/master/product.go#L90-L107) which will deserialize the resource based on whether it's a string or a hash.
