### ISSUE TITLE
card object ThreeDSecure

### ISSUE THREAD

**Issue by araufdogan** [stripe/stripe-go#696]
I have cards associated to customers. Card object (stripe.Card) has ThreeDSecure field but this field always nil.

How can i know card supports three d secure status (like required, recommended or optional) before charge? 

I try to create card source from server side using card id, but it giving always errors.

Is there any good server-side source creation and three d secure docs?

----------

```go
params := &stripe.SourceObjectParams{
    Type: stripe.String("card"),
    Usage: stripe.String("single_use"),
    TypeData: map[string]string{"card": "card_1DC1SFCRcrzTiRo1PGmxxxx"},
}
s, err := source.New(params)
```

`{"status":400,"message":"Received an unknown parameter for payment method `card`: card[card].","param":"card[card]","request_id":"req_UCQTsC9TXsIED4","type":"invalid_request_error"}`

----------

```go
params := &stripe.SourceObjectParams{
Type: stripe.String("card"),
Usage: stripe.String("single_use"),
TypeData: map[string]string{"card": "card_1DC1SFCRcrzTiRo1PGmxxxx"},
Customer: stripe.String("cus_DL3JdfYKYxxxx"),
}
s, err := source.New(params)
```

`{"status":400,"message":"Received unknown parameters: type, card","param":"type","request_id":"req_8iPUhxiwAjfgkb","type":"invalid_request_error"}`

----------

**Comment by remi-stripe** [comment]
@araufdogan At the moment, we have not built a way to convert a Card object (card_XXXXX) in a 3D Secure Source. Source objects are completely separate from Card objects in our API to avoid any confusion. Cards are the "old way" which we have used for years and Sources are newer and were shipped a year or two ago. 

The concept behind Sources is that it's an abstraction over all payment methods. You have one object that can be a Card but also a 3D Secure source, a Bank account in the EU or other countries, an Alipay account, etc. And most of your code handles those sources in a more generic way.

The idea in your situation would be to collect card details again for those customers but create *sources* client-side instead of *tokens*. This is documented in Elements here: https://stripe.com/docs/stripe-js/reference#stripe-create-source

Once you have a Card Source you can turn it into a 3DS Source as documented here: https://stripe.com/docs/sources/three-d-secure#create-3ds-source
