### ISSUE TITLE
NewIdempotencyKey repeats value for leap seconds

### ISSUE THREAD

**Issue by jmhodges** [stripe/stripe-go#71]
NewIdempotencyKey is not actually idempotent. If time moves backwards (as it will to every machine running NTP this June when the leap second hits), this code will produce the same key many times. https://github.com/stripe/stripe-go/blob/master/params.go#L58

Instead, just pull 128 bits from crypto/rand.Read. That will be enough randomness to not collide for the lifetime of the universe.

The previous leap second in 2012 did not go well. http://www.wired.com/2012/07/leap-second-bug-wreaks-havoc-with-java-linux/

**Comment by cosn** [comment]
Fair point, will update. Thanks!

**Comment by cosn** [comment]
Updated! I don't think using 128 bits is worth it since I don't care about this being cryptographically secure. I kept the `UnixNano` since I like being able to correlate with the client time, and added a 4-byte random base64-encoded string which should give us sufficient entropy for concurrent usage, while keeping things still moderately readable (otherwise, I would have just gone for a UUID)
