### ISSUE TITLE
Feature request: Leveled logging

### ISSUE THREAD

**Issue by mickeyreiss** [stripe/stripe-go#813]
It would be useful to pipe stripe-go's internal log levels into our logging framework (e.g. [logrus](https://github.com/sirupsen/logrus/), e.g. [zap](https://go.uber.org/zap)).

This way, we could keep diagnostic level logs turned on in production, but monitor error-level logs more closely.

I think there is a backwards compatibility problem here that could be solved by adding a new, leveled log interface in addition to the existing `Printfer`. For example, it could be a new interface `Logfer`.

**Comment by brandur-stripe** [comment]
Yeah, I've been thinking that we should do this for a while — the current `Printfer` interface is kind of the worst of all worlds in that it's not very functional *and* the log level system is quite unintuitive.

> I think there is a backwards compatibility problem here that could be solved by adding a new, leveled log interface in addition to the existing `Printfer`. For example, it could be a new interface `Logfer`.

Yeah, +1.

I'm tagging this as "future" for now, but I'll try to take a crack at it soon.

**Comment by brandur-stripe** [comment]
Okay, I'm close to having a patch together for this. Here's the interface that I'm thinking about exporting:

``` go
type LeveledLoggerInterface interface {
	// Function names here are ordered according to severity.

	Debugf(format string, v ...interface{})
	Infof(format string, v ...interface{})
	Warnf(format string, v ...interface{})
	Errorf(format string, v ...interface{})
}
```

This design is based on both [logrus](https://github.com/sirupsen/logrus/) as well as the Go standard library's [log](https://golang.org/pkg/log/) package, whose convention Logrus seems to have been trying to follow as much as possible.

Internally, we'll have a `leveledLoggerPrintferShim` that implements it and keeps current uses of `Logger` forwards compatible with identical behavior.

You'll also be able to plug your own into a new global variable with similar design to the current `Logger`:

``` go
var DefaultLeveledLogger LeveledLoggerInterface
```

This will be immediately compatible with Logrus so that you can do this:

``` go
stripe.DefaultLeveledLogger = logrus.New()
```

I was trying to find a way of making it compatible with Zap as well, but I wasn't able to do so. They didn't follow the standard library's convention, but worse yet, their signatures require a custom `Entry` type:

``` go
func (log *Logger) Info(msg string, fields ...Field)
```

I definitely don't want to bring Zap in as a dependency (even for a subpackage), so my pitch is that our recommendation will be for Zap users to build their own thin shim that's compatible with `LeveledLoggerInterface`, which should only be about a dozen lines of code.

Unfortunately, using the standard library's `log` will also require a shim because they used very unusual levels (there's only printf / fatal / panic). I wouldn't be opposed for including a shim to this logger right in stripe-go though — we're already importing the log package anyway.

@mickeyreiss I just wanted to check in to see if you see any clever techniques for wide compatibility between  logrus/zap/log that I hadn't thought of. Thanks!

**Comment by mickeyreiss** [comment]
This looks great!

I think it's fine for the stripe library to follow generalized go conventions. If it becomes a problem, shims could be maintained by the community in a `contrib` subpackage.

For reference, [the grpc middleware library](https://github.com/grpc-ecosystem/go-grpc-middleware/tree/v1.0.0/logging) does something similar-ish.

**Comment by brandur-stripe** [comment]
Thans @mickeyreiss! And interesting note on GRPC's contrib shims — I could definitely see us taking a similar path.  Opened a PR at #818.

**Comment by tjasko** [comment]
> I was trying to find a way of making it compatible with Zap as well, but I wasn't able to do so. They didn't follow the standard library's convention, but worse yet, their signatures require a custom Entry type...

For those who might come here, there's no need to use a shim with Zap. Zap's sugared logger (`zap.S()`) satisfies the `LeveledLoggerInterface` interface.

**Comment by brandur-stripe** [comment]
Thanks @tjasko. I'll update my comment above.
