### ISSUE TITLE
App Engine: "Call error 3: invalid security ticket"

### ISSUE THREAD

**Issue by mndrix** [stripe/stripe-go#86]
The documented approach for using this package on App Engine works for the first HTTP request, but never again.  Specifically, the documentation says to call

```go
stripe.SetHTTPClient(urlfetch.Client(appengine.NewContext(r)))
```

That creates and uses an HTTP client which is only valid for the life of the current HTTP request (`r`).  On the next request, one calls `stripe.SetHTTPClient` again.  That sets the default HTTP client but doesn't change the API backend, which still references the HTTP client from the first request.

A second HTTP request might call something like `customer.New(...)` which calls `stripe.GetBackend(stripe.APIBackend)` which returns a backend referring to an HTTP client from the first request.  Using that HTTP client gives an error like:

```
Post https://api.stripe.com/v1/customers: Call error 3: invalid security ticket: 6e2752a700a25c35
```

A better incantation for App Engine is something like:

```go
stripe.SetBackend(stripe.APIBackend, nil)
stripe.SetHTTPClient(urlfetch.Client(appengine.NewContext(r)))
```

I'd submit a pull request, but I'm not sure if this should be corrected in the documentation, in `SetHTTPClient` or in `GetBackend`

Somewhat related, using a global HTTP client in App Engine is bound to cause trouble when simultaneous requests want to call Stripe APIs.  Both goroutines will contend over stripe.httpClient and at most one goroutine can win.  I wish I could recommend a good solution to that problem.

**Comment by cosn** [comment]
Apologies for the delay on this one. Since I haven't use AE much, I'm pretty open to suggestions on how to best fix this. Seems like doc fix is the quickest thing, which you're more than welcome to update and I'm happy to get merged. I'm also open to a code change if we think it's better.

Thanks!

**Comment by pedromg** [comment]
Experiencing same issue here:
Post https://api.stripe.com/v1/charges: Call error 3: invalid security ticket: d347a19e5951563d 
Testing several requests

**Comment by pedromg** [comment]
<script src="https://gist.github.com/pedromg/629d8309f4c8c4a39bc9.js"></script>

**Comment by munjal** [comment]
I'm really surprised that Stripe doesn't really give a shit about this issue! It's been more than 5 months!!

**Comment by kyleconroy** [comment]
So I think this will work. 

```go
package example

import (
	"net/http"

	"appengine"
	"appengine/urlfetch"

	"github.com/stripe/stripe-go"
	"github.com/stripe/stripe-go/client"
)

func handler(w http.ResponseWriter, r *http.Request) {
	sc := &client.API{}
	httpClient := urlfetch.Client(appengine.NewContext(req))

	backends := Backends{
		API: stripe.BackendConfiguration{
			stripe.APIBackend, "https://api.stripe.com/v1", httpClient},
		Uploads: stripe.BackendConfiguration{
			stripe.UploadsBackend, "https://uploads.stripe.com/v1", httpClient},
	}

	sc.Init("sk_key", backends)

        // Use the client to make API calls.
	ch, err := sc.Charges.Get("ch_example_id", &stripe.ChargeParams{})
}
```

@munjal can you try this out and tell me if it works?

This isn't super pretty, so if it works, I think we'll add a `SetHTTPClient` method to client.

**Comment by kyleconroy** [comment]
@cosn what do you think of the following API?

```go
httpClient := urlfetch.Client(appengine.NewContext(r))
sc := client.New("sk_key", stripe.Backends(httpClient))
```

**Comment by cosn** [comment]
So basically you have a some `client` created and then you create new `sc` objects? Just making sure that's what was meant

**Comment by coreymgilmore** [comment]
Would love to see an "official" update and fix for this...especially at +5 months.

@mndrix's solution works but presents the single global http client issue.  If you are not making simultaneous calls to Stripe then this *should not* be an issue.  As of now it is best to do API calls in sequence (per r *http.Request) instead of concurrently with goroutines.

**Comment by kyleconroy** [comment]
@coreymgilmore did you try the fix I proposed above?

**Comment by coreymgilmore** [comment]
@kyleconroy I did try your proposed solution:
> httpClient := urlfetch.Client(appengine.NewContext(r))
> sc := client.New("sk_key", stripe.Backends(httpClient))

But this did not work.  I get a error: `undefined: client.New`. Doing some quick research, the "stripe-go/client" library does not have a "New" function [https://github.com/stripe/stripe-go/blob/master/client/api.go] hence the error.

**Comment by coreymgilmore** [comment]
@kyleconroy I did just try your earlier suggestion:

```go
 sc := &client.API{}
    httpClient := urlfetch.Client(appengine.NewContext(r))

    backends := Backends{
        API: stripe.BackendConfiguration{
            stripe.APIBackend, "https://api.stripe.com/v1", httpClient},
        Uploads: stripe.BackendConfiguration{
            stripe.UploadsBackend, "https://uploads.stripe.com/v1", httpClient},
    }

    sc.Init("sk_key", backends)
```

...and got this to work with some changes....

```go
sc := &client.API{}
	httpClient := urlfetch.Client(c)

	backends := stripe.Backends{
        API: stripe.BackendConfiguration{
            stripe.APIBackend, "https://api.stripe.com/v1", httpClient},
        Uploads: stripe.BackendConfiguration{
            stripe.UploadsBackend, "https://uploads.stripe.com/v1", httpClient},
    }

    sc.Init(stripePrivateKey, &backends)
```

Not sure is this is a better option though versus what @mndrix proposed.  First, his is only two lines: a lot cleaner and less redundant (no need to declare the backends). Second, I think your option still presents the single http client issue since all calls are being made from `sc`.

I think both options need to be tested but the docs definitely need to be updated asap.

**Comment by kyleconroy** [comment]
Yeah, sorry about that. The proposed two line solution is just an idea, not working code. Glad the second option worked.

You shouldn't be using the code @mndrix posted because it isn't thread safe. If you have two concurrent requests (a very likely scenario), you could end up using the wrong HTTP client. 

> Second, I think your option still presents the single http client issue since all calls are being made from sc

That httpClient should be initiated using the context from an app engine request. As long as you don't share `sc` among requests, it will be safe to use.

**Comment by kyleconroy** [comment]
The documentation has been updated: https://github.com/stripe/stripe-go/blob/master/README.md#google-appengine

I'm going to keep this open until we have the two line solution.

**Comment by coreymgilmore** [comment]
Hi @kyleconroy,

Thanks for updating the docs.  That should stop people from even seeing the error that started this thread.

Idea for making this a one liner: add the below function (with some edits) to the `stripe-go` package:

```go
func createAppengineStripeClient(c appengine.Context) *client.API {
	//create http client
	httpClient := urlfetch.Client(c)

	//create backends for http client
	//these are the stripe api backends that we need to communicate with
	backends := stripe.Backends{
		API: 		stripe.BackendConfiguration{stripe.APIBackend, "https://api.stripe.com/v1", httpClient},
		Uploads: 	stripe.BackendConfiguration{stripe.UploadsBackend, "https://uploads.stripe.com/v1", httpClient},
	}

	//initialize the client
	//this creates a client that uses our per-request httpclient
	sc := &client.API{}
	sc.Init("sk_key", &backends)

	//return the client to use in making charges, adding customer, getting data, etc.
	return sc
}
```

Then the only step to creating an `sc` client to use for a request is:
```go
c  := appengine.NewContext(r)
sc := createStripeClient(c)
````

Its a "one liner" for us, the users....not so much for Stripe.  Basically just pushes the `sc` creation function into the stripe library instead of the user's creating it (since every user on App Engine is going to do this exact same thing with the same code.  Plus, then the URLs can reference the URLs in the stripe library (currently they are not exported) so that user's do not make mistakes or if Stripe changes the URLs in the future.

Just an idea.  Maybe I will file a PR for it even though the use case is limited to GAE.

**Comment by mndrix** [comment]
> func createAppengineStripeClient(c appengine.Context) *client.API {

That would be grand.  Unfortunately, Go's type system would require that the `appengine` package be loaded.  That's probably not a package dependency that all stripe-go users want.  Although one could put this function in a stripe-go-ae package that adds a convenience wrapper for App Engine users.

**Comment by coreymgilmore** [comment]
@mndrix Very true. Missed that since I already have it loaded.  The wrapper seems like the best solution and/or just copy-pasting the func into your source.
