### ISSUE TITLE
Feature request: Downgrade log level for `card_error`s

### ISSUE THREAD

**Issue by mickeyreiss** [stripe/stripe-go#869]
Following up on #813, we've noticed error level logging for error responses of type `card_error`.

My understanding is that these errors require user input to resolve them, so they are normal processing and not possible to resolve with backend code.

Is this log level intentional, or would it make sense to downgrade these types of error logs?

**Comment by brandur-stripe** [comment]
Hm yes, good point — we should try to avoid logging errors for actions that an integration couldn't possibly have executed successfully.

@ob-stripe @remi-stripe Can I get a quick sanity check for an idea on this one? We at least attempt to make a status code distinction between requests that failed due to bad input parameters as status 400 and requests that failed through bad user input (as opposed to bad integration input) as status 402.

What do you think about tweaking this code such that status 400 errors continue to log as errors (with the idea that an integration owner can fix the problem), and changing status 402 errors to log as info (and maybe with a tweaked message to suggest it was a user input problem)?

I'm not sure that it will address all problems, but it's consistent with how 400/402 are described in our documentation, and seems pretty clean to me.

**Comment by remi-stripe** [comment]
That seems fine to me!

**Comment by ob-stripe** [comment]
👍 sgtm too.

**Comment by brandur-stripe** [comment]
Excellent! Thanks guys — opened #874.
