### ISSUE TITLE
Add secret and object field to EphemeralKey struct

### ISSUE THREAD

**Issue by uneight** [stripe/stripe-go#873]

**Comment by remi-stripe** [comment]
@uneight The Ephemeral Key is a particular object in our libraries. It's not supposed to be parsed or used directly. Instead, you're supposed to send the raw JSON to our mobile SDKs (iOS and Android) for those to use the key on your behalf. That's why the resource doesn't have any of the usual fields at the moment.

You should never have to access the secret or the object yourself. Would you be able to provide a bit more details about your integration to clarify why you need those?
