### ISSUE TITLE
ErrorCode doesn't cover all of codes listed in official doc

### ISSUE THREAD

**Issue by wawoon** [stripe/stripe-go#896]
# Background

I'm creating GraphQL API which uses Stripe API to provide payment feature with our client application, and I want to provide ErrorCode as enum in GraphQL API.

Then I investigated the error codes api [document](https://stripe.com/docs/error-codes). But I found some problems.

# What to be fixed

- The `ErrorCode`  doesn't cover all types listed in [docs](https://stripe.com/docs/error-codes)
- The code of "invalid_swipe_data" is not listed in [docs](https://stripe.com/docs/error-codes)

# Solution

I think this problem can be fixed by just adding missing error codes, and removing `invalid_swipe_data` value.

**Comment by remi-stripe** [comment]
@wawoon The list of errors predates the time we shipped that list of error codes. Originally, the API only had a handful of unique error codes mostly tailored for declines and high level errors. That's why the list seems different. The `invalid_swipe_data` is a real error code though it's gated and not accessible by all integrations.

I've opened a PR https://github.com/stripe/stripe-go/pull/897 to add all existing error codes from that documentation
