### ISSUE TITLE
API for interation test from backend 

### ISSUE THREAD

**Issue by camiloperezv** [stripe/stripe-go#912]
Hi. We are making the migration with SCA and payment confirmation.

There is some request from the client-side which we would like to do from the backend. I already have the request for `createPaymentMethod` but for `handleCardAction` i wasn't able to emulate that from backend, there is some API I can call to get the PaymentIntentClientSecret?

Thanks

**Comment by remi-stripe** [comment]
@camiloperezv The `PaymentIntent` secret is always on the `PaymentIntent` resource whenever you create, update or retrieve one. It's defined here: https://github.com/stripe/stripe-go/blob/master/paymentintent.go#L235

What you're describing though is not possible server-side even for testing. `handleCardAction` has to be done client-side since it will trigger the 3DS modal.

I'm going to close this out as it's more an API question and I'd recommend reaching out to our support team instead: https://support.stripe.com/contact
