### ISSUE TITLE
Create subscription with coupon (duration=Once) returns Discount:(*stripe.Discount)(nil)

### ISSUE THREAD

**Issue by layby42** [stripe/stripe-go#944]
Create subscription with coupon (duration=Once) returns Discount:(*stripe.Discount)(nil).
Stripe Dashboard shows that coupon was applied to subscription:

```
Method POST
URL /v1/subscriptions
Status 200
Version 2019-08-14 (latest)
Source Stripe/v1 GoBindings/62.8.2
coupon — 20-once
subscription — sub_XXXXXXXXX
```
Re-query subscription from Stripe by ID does not help, still Discount:(*stripe.Discount)(nil).

Create subscription with coupon (duration=Forever) returns Discount with correct coupon.

Update subscription with coupon (duration=Once or duration=Forever) results in subscription with Discount with correct coupon.

**Comment by remi-stripe** [comment]
@layby42 This is expected. When the Subscription is created, it creates an Invoice for the first Charge. This consumes the coupon that was applied immediately so at creation the Subscription does not have a Discount anymore on it since it was consumed.

When you update the Subscription, no charge happens, so the discount is active until it's consumed by an Invoice.
